
<li class="hbpcbox">
<div class="needsolbox">
<h3 class="domentitle"><span><a
	href="/object-article/list/category/<?php
	echo NEWS_DISCUSSION;
	?>"
	class="discuss"><img
	src="<?php
	print $this->defaultSkinImagesUrl;
	?>spacer.gif"
	alt="قضية للنقاش" title="قضية للنقاش" width="124" height="21" /></a></span>
</h3>
<div class="domendata">
<div class="cleaner padritlft5"><a
	href="/object-article/view/id/<?php
	echo $this->newsDiscussionList [0] ['id'];
	?>/title/<?php
	echo $this->newsDiscussionList [0] ['title'];
	?>"><img
	class="thumb fr"
	alt="<?php
	echo $this->newsDiscussionList [0] ['photo_alias'];
	?>"
	title="<?php
	echo $this->newsDiscussionList [0] ['photo_alias'];
	?>"
	src="<?php
	echo $this->newsDiscussionList [0] ['imageUrl'];
	?>"></a>
<h2><a
	href="/object-article/view/id/<?php
	echo $this->newsDiscussionList [0] ['id'];
	?>/title/<?php
	echo $this->newsDiscussionList [0] ['title'];
	?>"><?php
	echo $this->cleanHtml ( $this->newsDiscussionList [0] ['title'] );
	?></a></h2>
<p class="margthalf"><?php
echo $this->subString ( $this->newsDiscussionList [0] ['full_text'], $this->start, 300 ) . '.....';
?></p>
</div>
</div>
</div>
</li>