            <li class="hbpcboxlast">
                <div class="needsolbox">
                    <h3 class="domentitle">
                        <span><a href="/object-article/list/category/<?php echo NEWS_BEAUTY; ?>" class="hbtitle"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="صحة وجمال" title="صحة وجمال" width="110" height="21" /></a></span>
                    </h3>
                    <div class="domendata">
                        <ul class="newslst padritlft5">
							<?php
							$countBeauty= count($this->newsBeautyList);
							for($k=0; $k< $countBeauty; $k++ ){ 
							?>	
                            <li class="cleaner<?php echo ($k == ($countBeauty)-1 )?' last':''; ?>">
                                <a href="/object-article/view/id/<?php echo $this->newsBeautyList[$k]['id']; ?>/title/<?php echo $this->newsBeautyList[$k]['title']; ?>"><img src="<?php echo $this->newsBeautyList[$k]['imageUrl']; ?>" title="<?php echo $this->newsBeautyList[$k]['photo_alias']; ?>" alt="<?php echo $this->newsBeautyList[$k]['photo_alias']; ?>" class="thumb fr"></a>
                                <h2 class="fnt11"><a href="/object-article/view/id/<?php echo $this->newsBeautyList[$k]['id']; ?>/title/<?php echo $this->newsBeautyList[$k]['title']; ?>"><?php echo $this->cleanHtml ( $this->newsBeautyList[$k]['title'] ); ?></a></h2>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </li>