            <li class="hbpcbox">
                <div class="complainbox">
                    <h3 class="domentitle">
                        <span><a href="/object-article/list/category/<?php echo NEWS_COMPLAINS; ?>" class="complain"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="شكاوى" title="شكاوى" width="73" height="21" /></a></span>
                    </h3>
                    <div class="domendata">
                        <ul class="newslst padritlft5">
                            <li class="cleaner">
                            <?php
							$countComplains= count($this->newsComplainsList);
							for($k=0; $k<= 1; $k++ ){ 
							?>                            
                                <div class="hafwdth fl">
                                	<a href="/object-article/view/id/<?php echo $this->newsComplainsList[$k]['id']; ?>/title/<?php echo $this->newsComplainsList[$k]['title']; ?>"><img class="thumb fr" alt="<?php echo $this->newsComplainsList[$k]['photo_alias']; ?>" title="<?php echo $this->newsComplainsList[$k]['photo_alias']; ?>" src="<?php echo $this->newsComplainsList[$k]['imageUrl']; ?>"></a>
                                    <h2 class="fnt11"><a href="/object-article/view/id/<?php echo $this->newsComplainsList[$k]['id']; ?>/title/<?php echo $this->newsComplainsList[$k]['title']; ?>" class="blak"><?php echo $this->cleanHtml ( $this->newsComplainsList[$k]['title'] ); ?></a></h2>
                                </div>
                            <?php } ?>
                            </li>
                            <li class="cleaner last">
                            <?php
							$countComplains= count($this->newsComplainsList);
							for($k=2; $k< $countComplains; $k++ ){ 
							?>
                                <div class="hafwdth fl">
                                	<a href="/object-article/view/id/<?php echo $this->newsComplainsList[$k]['id']; ?>/title/<?php echo $this->newsComplainsList[$k]['title']; ?>"><img class="thumb fr" alt="<?php echo $this->newsComplainsList[$k]['photo_alias']; ?>" title="<?php echo $this->newsComplainsList[$k]['photo_alias']; ?>" src="<?php echo $this->newsComplainsList[$k]['imageUrl']; ?>"></a>
                                    <h2 class="fnt11"><a href="/object-article/view/id/<?php echo $this->newsComplainsList[$k]['id']; ?>/title/<?php echo $this->newsComplainsList[$k]['title']; ?>" class="blak"><?php echo $this->cleanHtml ( $this->newsComplainsList[$k]['title'] ); ?></a></h2>
                                </div>
                            <?php } ?>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>