<div class="lftpanel">
            	<!--Quraan block-->
					<?php include './blocks/quraan.phtml'; ?>
                <!--end Quraan block-->
                <!--musharakat block-->
					<?php include './blocks/musharakat.phtml'; ?>
                <!--end musharakat block-->
                <p class="visitnum">99999999</p>
                <ul class="adslst">
                    <li class="margt1"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>ad1.jpg" alt="" width="172" height="128" /></a></li>
                    <li class="margt1"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>ad2.jpg" alt="" width="172" height="128" /></a></li>
                </ul>
            </div>