<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './html/meta.phtml'; ?>
<script type="text/javascript">
$(document).ready(function() {
	$('textarea.tinymce').tinymce({
		// Location of TinyMCE script
		script_url : '<?php print $this->defaultSkinJsUrl; ?>tiny_mce/tiny_mce.js',
		
		// General options
		theme : "advanced",
		plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
		
		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,|,insertdate,inserttime,preview,|,forecolor,backcolor",
		theme_advanced_buttons3 : "", 
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		
		// Example content CSS (should be your site CSS)
		content_css : "<?php print $this->defaultSkinJsUrl; ?>tiny_mce/themes/advanced/skins/default/content.css",
		
		// Drop lists for link/image/media/template dialogs
		external_image_list_url : "<?php print $this->photo_list; ?>",
		media_external_list_url : "<?php print $this->media_list; ?>",
		
		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
});
</script>
</head>
<body class="tundra">

<!--container-->
<div class="container">
<?php include './html/header.phtml'; ?>
<?php include './html/menu.phtml'; ?>
<?php include './html/notification.phtml'; ?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<!--end lftnav-->

<!--srch-rslt-->
<div class="srch-rslt">
<h3 class="fl pagetitle margthaf"><?php echo $this->__ ( 'Object_Add New Defaulr' ); ?></h3>
<!-- 
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="2" class="emptbtn" type="submit"><?php echo $this->__ ( 'Object_Save And Continue Edit' ); ?></button></em></a>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="1" class="emptbtn" type="submit"><?php echo $this->__ ( 'Object_Save' ); ?></button></em></a>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="0" class="emptbtn" type="reset"><?php echo $this->__ ( 'Object_Reset' ); ?></button></em></a>
-->
<a href="javascript:history.go(-1)" class="backbtn"><em><button name="btn_submit" value="-1" class="emptbtn" type="button" onlcick="javascript:history.go(-1);"><?php echo $this->__ ( 'Object_Back' ); ?></button></em></a>
</div>
<!--end srch-rslt-->

<!--ritcont-->
<div class="entrdata">
	<div class="entrdcont">
		<div class="wdthauto">
			<?php 
			 echo $this->form;
			 echo $this->dojo ();
			?>
		</div>
	</div>
</div>


</div>
<!--end maincont-->
</div>
<!--end content-->
<?php include './html/footer.phtml'; ?>
</div>
<!--end container-->
</body>
</html>
