
<li class="tab" title="conttab11"><a href="javascript:void(0);"><span><?php
echo $this->__ ( 'Object_Advanced' );
?></span></a></li>
<li class="tab" title="conttab12"><a href="javascript:void(0);"><span><?php
echo $this->__ ( 'Object_Meta Data' );
?></span></a></li>
<!-- <li class="tab" title="conttab13"><a href="javascript:void(0);"><span><?php
echo $this->__ ( 'Object_Design' );
?></span></a></li> -->