<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
include './html/meta.phtml';
?>
</head>
<body>

<!--container-->
<div class="container">
<?php
include './html/header.phtml';
?>
<?php

include './html/menu.phtml';
?>
<?php

include './html/notification.phtml';
?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<div class="lftnav">
<h3 class="margb1"><?php
echo $this->__ ( 'Object_Catagory' );
?></h3>
<ul>
	<li class="tab active" title="conttab10"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Object_Files' );
	?></span></a></li>
	<li class="tab" title="conttab11"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Object_Advanced' );
	?></span></a></li>
</ul>
</div>
<!--end lftnav--> <!--ritcont-->
<form action="" method="post" enctype="multipart/form-data">
<div class="ritcont"><!--srch-rslt-->
<div class="srch-rslt">
<h3 class="fl pagetitle margthaf"><?php
echo $this->__ ( 'Object_Add New Object' );
?></h3>
<a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="2" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Save And Continue Edit' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="1" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Save' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="0" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Reset' );
?></button>
</em></a> <a href="javascript:history.go(-1)" class="backbtn"><em>
<button name="btn_submit" value="-1" class="emptbtn" type="button"
	onlcick="javascript:history.go(-1);"><?php
	echo $this->__ ( 'Object_Back' );
	?></button>
</em></a></div>
<!--end srch-rslt--> <!--conttab10 File -->
<div class="mytabscont" id="conttab10" style="display: block;">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Object_Information' );
?></h2>
<div class="entrdcont">
<div class="wdthauto"><input type="hidden" id="Id" name="Id"
	value="<?php
	print $this->sanitized->Id->value;
	?>" /> <input
	type="hidden" id="token" name="token"
	value="<?php
	print $this->sanitized->token->value;
	?>" />
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Name' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="nameFile" name="nameFile"
			value="<?php
			print $this->sanitized->nameFile->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->nameFile->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->nameFile->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Label' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="labelFile" name="labelFile"
			value="<?php
			print $this->sanitized->labelFile->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->labelFile->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->labelFile->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Description' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="descriptionFile" name="descriptionFile"
			value="<?php
			print $this->sanitized->descriptionFile->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->descriptionFile->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->descriptionFile->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Upload' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="file" class="inptfile"
			id="uploadFile" name="uploadFile" />
		<div class="validat" style="<?php
		print $this->sanitized->uploadFile->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->uploadFile->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	if (! empty ( $this->directoryList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Folders' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct"
			id="directoryId" name="directoryId">
		<?php
		echo $this->directoryList;
		?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->directoryId->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->directoryId->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="directoryId" value="1" /></td>
	</tr>
	<?php
	}
	?>
	<?php
	if (! empty ( $this->categoryList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Category' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct"
			id="category" name="category">
		<?php
		echo $this->categoryList;
		?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->category->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->category->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="category" value="1" /></td>
	</tr>
	<?php
	}
	?>
</table>
</div>
</div>
</div>
</div>
<!--end conttab10--> <!--conttab11 Advanced -->
<div class="mytabscont" id="conttab11" style="display: none">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Object_Advanced' );
?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Comments' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="comment" name="comment"
			value="<?php
			print $this->sanitized->comment->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->comment->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->comment->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Options' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="option" name="option"
			value="<?php
			print $this->sanitized->option->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->option->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->option->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop">&nbsp;</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="checkbox" class="intchk fl"
				id="published" name="published" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->published->value) ? 'checked="checked"' : '';
				?> />
			<label for="published" class="inptlabl fl"><?php
			echo $this->__ ( 'Object_Published' );
			?></label><br />
			<div class="validat" style="<?php
			print $this->sanitized->published->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->published->errorMessage;
		?></div>
			</li>
			<li class="cleaner"><input type="checkbox" id="approved"
				class="intchk fl" name="approved" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->approved->value) ? 'checked="checked"' : '';
				?> />
			<label for="approved" class="inptlabl fl"><?php
			echo $this->__ ( 'Object_Approved' );
			?></label><br />
			<div class="validat" style="<?php
			print $this->sanitized->approved->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->approved->errorMessage;
		?></div>
			</li>
		</ul>
		</td>
	</tr>
</table>
</div>
</div>
</div>
</div>
<!--end conttab11--> <!--end ritcont--></div>
</form>
</div>
<!--end maincont--></div>
<!--end content-->
<?php
include './html/footer.phtml';
?>
</div>
<!--end container-->
</body>
</html>
