<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
include './html/meta.phtml';
?>
</head>
<body>

<!--container-->
<div class="container">
<?php
include './html/header.phtml';
?>
<?php

include './html/menu.phtml';
?>
<?php

include './html/notification.phtml';
?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<div class="lftnav">
<h3 class="margb1"><?php
echo $this->__ ( 'Object_Add New Source' );
?></h3>
<ul>
	<li class="tab active" title="conttab4"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Object_Source' );
	?></span></a></li>
	<li class="tab" title="conttab11"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Object_Advanced' );
	?></span></a></li>
</ul>
</div>
<!--end lftnav--> <!--ritcont-->
<form action="" method="post">
<div class="ritcont"><!--srch-rslt-->
<div class="srch-rslt"><!-- <h3 class="fl pagetitle margthaf"><?php
echo $this->__ ( 'Object_Add New Source' );
?></h3> -->
<a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="2" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Save And Continue Edit' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="1" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Save' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="0" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Reset' );
?></button>
</em></a> <a href="javascript:void(0);" class="backbtn"><em>
<button name="btn_submit" value="-1" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Object_Back' );
?></button>
</em></a></div>
<!--end srch-rslt--> <!--conttab4 Source -->
<div class="mytabscont" id="conttab4" style="display: block">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Object_Source' );
?></h2>
<div class="entrdcont">
<div class="wdthauto"><input type="hidden" id="Id" name="Id"
	value="<?php
	print $this->sanitized->Id->value;
	?>" /> <input
	type="hidden" id="token" name="token"
	value="<?php
	print $this->sanitized->token->value;
	?>" />
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Title' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="nameSource" name="nameSource"
			value="<?php
			print $this->sanitized->nameSource->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->nameSource->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->nameSource->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Description' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="descriptionSource" name="descriptionSource"
			value="<?php
			print $this->sanitized->descriptionSource->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->descriptionSource->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->descriptionSource->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	if (! empty ( $this->sourceTypeList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Source Type' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct"
			id="sourceType" name="sourceType">
			<?php
		print $this->sourceTypeList;
		?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->sourceType->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->sourceType->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="sourceType" value="1" /></td>
	</tr>
	<?php
	}
	?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_URL' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="urlSource" name="urlSource"
			value="<?php
			print $this->sanitized->urlSource->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->urlSource->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->urlSource->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	if (! empty ( $this->countrySourceList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Country' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct"
			id="countrySource" name="countrySource">
			<?php
		echo $this->countrySourceList;
		?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->countrySource->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->countrySource->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="countrySource" value="1" /></td>
	</tr>
	<?php
	}
	?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Time Delay' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="timeDelay" name="timeDelay"
			value="<?php
			print $this->sanitized->timeDelay->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->timeDelay->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->timeDelay->errorMessage;
		?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
</div>

<!--conttab11 Advanced -->
<div class="mytabscont" id="conttab11" style="display: none">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Object_Advanced' );
?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Comments' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="comment" name="comment"
			value="<?php
			print $this->sanitized->comment->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->comment->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->comment->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Options' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="option" name="option"
			value="<?php
			print $this->sanitized->option->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->option->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->option->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Publish From' );
		?>:</td>
		<td class="lablvalue jstalgntop">
		<div class="calen_beside"><input type="text"
			class="inpttxt wdth70 slctdate" id="slct_date2" name="publishFrom"
			value="<?php
			print $this->sanitized->publishFrom->value;
			?>" /></div>
		<div class="validat" style="<?php
		print $this->sanitized->publishFrom->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->publishFrom->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Object_Publish To' );
		?>:</td>
		<td class="lablvalue jstalgntop">
		<div class="calen_beside"><input type="text"
			class="inpttxt wdth70 slctdate" id="slct_date3" name="publishTo"
			value="<?php
			print $this->sanitized->publishTo->value;
			?>" /></div>
		<div class="validat" style="<?php
		print $this->sanitized->publishTo->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->publishTo->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop">&nbsp;</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="checkbox" class="intchk fl"
				id="published" name="published" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->published->value) ? 'checked="checked"' : '';
				?> />
			<label for="published" class="inptlabl fl"><?php
			echo $this->__ ( 'Object_Published' );
			?></label><br />
			<div class="validat" style="<?php
			print $this->sanitized->published->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->published->errorMessage;
		?></div>
			</li>
			<li class="cleaner"><input type="checkbox" id="approved"
				class="intchk fl" name="approved" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->approved->value) ? 'checked="checked"' : '';
				?> />
			<label for="approved" class="inptlabl fl"><?php
			echo $this->__ ( 'Object_Approved' );
			?></label><br />
			<div class="validat" style="<?php
			print $this->sanitized->approved->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->approved->errorMessage;
		?></div>
			</li>
		</ul>
		</td>
	</tr>
	<?php
	if (! empty ( $this->afterIdList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Locale_Order' );
		?>:</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="radio" id="order" class="intchk fl"
				name="order" value="0"
				<?php
		if (0 == $this->sanitized->order->value || 'after' != $this->sanitized->order->value) {
			echo 'checked="checked"';
		}
		?> /> <label for="order" class="inptlabl fl"><?php
		echo $this->__ ( 'Locale_At the beginning of the list' );
		?></label><br />
			<div class="validat" style="<?php
		print $this->sanitized->order->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->order->errorMessage;
		?></div>
			</li>
			<li class="cleaner"><input type="radio" id="order" class="intchk fl"
				name="order" value="-1"
				<?php
		echo (- 1 == $this->sanitized->order->value) ? 'checked="checked"' : '';
		?> />
			<label for="order" class="inptlabl fl"><?php
		echo $this->__ ( 'Locale_After' );
		?></label><br />
			<select class="inptslct" id="afterId" name="afterId">
				<?php
		echo $this->afterIdList;
		?>
				</select>
			<div class="validat" style="<?php
		print $this->sanitized->afterId->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->afterId->errorMessage;
		?></div>
			</li>
		</ul>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="order" value="0" /></td>
	</tr>
	<?php
	}
	?>
</table>
</div>
</div>
</div>
</div>
<!--end conttab11--></div>
<!--end ritcont-->
</form>
</div>
<!--end maincont--></div>
<!--end content-->
<?php
include './html/footer.phtml';
?>
</div>
<!--end container-->
</body>
</html>
