<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './html/meta.phtml'; ?>
</head>
<body>
<!--container-->
<div class="container">
<?php include './html/header.phtml'; ?>
<?php include './html/menu.phtml'; ?>
<?php include './html/notification.phtml'; ?>
<!--content-->
<form method="get" action="" id="frm">
<div>
	<input type="hidden" id="token" name="token" value="<?php print $this->sanitized->title->value; ?>" />
	<input type="hidden" id="actionURI" value="<?php print $this->sanitized->actionURI->value; ?>" />
</div>
<div class="content">
<div class="srch-rslt cleaner">
<h3 class="fl pagetitle margthaf"><?php echo $this->__ ( 'Object_Object' ); ?></h3>
<a href="<?php print $this->sanitized->actionURI->value; ?>add" class="add-btn"><em><?php echo $this->__ ( 'Object_Add New Object' ); ?></em></a></div>
<!--filtration-->
<div class="filtration cleaner">
<button type="button"
	onclick="return changeFormAction('approve', 'post');" name="approve"
	id="approve" class="inpt-btn fr"><span><em><?php echo $this->__ ( 'Object_Approve' ); ?></em></span></button>
<button type="button"
	onclick="return changeFormAction('publish', 'post');" name="publish"
	id="publish" class="inpt-btn fr"><span><em><?php echo $this->__ ( 'Object_Publish' ); ?></em></span></button>
<button type="button"
	onclick="return changeFormAction('showInList', 'post');"
	name="showInList" id="showInList" class="inpt-btn fr"><span><em><?php echo $this->__ ( 'Object_Show In List' ); ?></em></span></button>
<button type="button"
	onclick="return changeFormAction('delete', 'post');" name="delete"
	id="delete" class="inpt-btn fr"><span><em><?php echo $this->__ ( 'Object_Delete' ); ?></em></span></button>
	<select style="float: left;" name="status">
	    <option <?php echo ($this->sanitized->status->value == 'Yes') ? 'selected="selected"' : '' ; ?> value="Yes"><?php echo $this->__('Yes Option'); ?></option>
	    <option <?php echo ($this->sanitized->status->value == 'No') ? 'selected="selected"' : '' ; ?> value="No"><?php echo $this->__('No Option'); ?></option>
	</select>
	<input type="hidden" id="redirectURI" name="redirectURI" value="<?php print $this->sanitized->redirectURI->value; ?>" />
</div>
<!--end filtration-->

<!--srch-rsult-->
<table class="srch-rsult">
	<tr class="heading">
		<th class="jstalgntop col1"><input type="checkbox" name="selectAll" id="selectAll" /></th>
		<th class="jstalgntop col1"><a
			href="<?php echo $this->sort->title->href; ?>"
			class="<?php echo $this->sort->title->cssClass; ?>"><span
			class="<?php echo $this->sort->title->cssClass; ?>"><?php echo $this->__ ( 'Object_Title' ); ?></span></a></th>
		<th class="jstalgntop col4"><a
			href="<?php echo $this->sort->show_in_list->href; ?>"
			class="<?php echo $this->sort->show_in_list->cssClass; ?>"><span
			class="<?php echo $this->sort->show_in_list->cssClass; ?>"><?php echo $this->__ ( 'Object_Show In List' ); ?></span></a></th>
		<th class="jstalgntop colyesno"><a
			href="<?php echo $this->sort->published->href; ?>"
			class="<?php echo $this->sort->published->cssClass; ?>"><span
			class="<?php echo $this->sort->published->cssClass; ?>"><?php echo $this->__ ( 'Object_Publish' ); ?></span></a></th>
		<th class="jstalgntop colyesno"><a
			href="<?php echo $this->sort->approved->href; ?>"
			class="<?php echo $this->sort->approved->cssClass; ?>"><span
			class="<?php echo $this->sort->approved->cssClass; ?>"><?php echo $this->__ ( 'Object_Aprrove' ); ?></span></a></th>
		<th class="jstalgntop col5"><a
			href="<?php echo  $this->sort->date_added->href; ?>"
			class="<?php echo $this->sort->date_added->cssClass; ?>"><span
			class="<?php echo $this->sort->date_added->cssClass; ?>"><?php echo $this->__ ( 'Object_Date Added' ); ?></span></a></th>
		<th class="jstalgntop col1"><span><?php echo $this->__ ( 'Object_Contains' ); ?></span></th>
		<!-- <th class="jstalgntop tools last"><span><?php echo $this->__ ( 'Object_Tools' ); ?></span></th> -->
	</tr>


	<?php 
	if (!empty($this->objectList)) {
			foreach ($this->objectList as $key => $value) {
				echo '<tr>';
				echo '<td class="jstalgntop" style="text-align: center;"><input type="checkbox" name="objectId[' . $value['object_id'] . ']" id="check" value="Yes" /></td>';
				//echo '<td class="jstalgntop"><a href="' . $value['largePhotoSRC'] . '" target="_blank"><img src="' . $value['photoSRC'] . '" border="0px" alt="' . $value['title'] . '" title="' . $value['title'] . '" /></a></td>';
				echo '<td class="jstalgntop">' . $value['title'] . '</td>';
				echo '<td class="jstalgntop">' . $this -> __($value['object_show_in_list']) . '</td>';
				echo '<td class="jstalgntop">' . $this -> __($value['object_published']) . '</td>';
				echo '<td class="jstalgntop">' . $this -> __($value['object_approved']) . '</td>';
				echo '<td class="jstalgntop">' . $value['object_date_added'] . '</td>';
				echo '<td class="jstalgntop">';
				if (!empty($value['flvURL']))
					echo '<a href="' . $value['flvURL'] . '" target="_blank"><img src="' . $value['thumbURL'] . '.jpg" border="0px" alt="' . $value['object_video_extension'] . '" title="' . $value['object_video_extension'] . '" /></a><br />';
				if (!empty($value['largePhotoSRC']))
					echo '<a href="' . $value['largePhotoSRC'] . '" target="_blank"><img src="' . $value['photoSRC'] . '" border="0px" alt="' . $value['object_photo_alias'] . '" title="' . $value['object_photo_alias'] . '" /></a><br />';
				if (!empty($value['fileURL']))
					echo '<a href="' . $value['fileURL'] . '" target="_blank"><img src="' .$this->defaultSkinImagesUrl . substr($value['object_file_extension'], 1) . '.png" border="0px" alt="' . $value['object_file_extension'] . '" title="' . $value['object_file_extension'] . '" /></a>';
				echo '</td>';
				echo '<!-- <td class="jstalgntop last"><a href="/admin/handle/pkg/object/action/edit/id/' . $value['id'] . '"
						class="modify fl" title="Edit"></a> <a href="/admin/handle/pkg/object/action/view/id/' . $value['id'] . '"
			class="preview fl" title="Preview"></a></td> -->';
				echo '</tr>';
			}
	} 
	?>

</table>

<!--begin paging-->
<?php include './html/paging.phtml'; ?>
<!--end paging-->

</div>
<!--end content-->
</form>
<?php include './html/footer.phtml'; ?>
</div>
<!--end container-->
</body>
</html>
