<div class="nav" style="overflow:hidden">
	<div class="navCon">
		<ul>
        	<li class="first"><a href="<?php echo $this -> rootUrl?>">Home</a></li>
            <li><a href="/vehicle/default/for/sale">Vehicle for sale</a></li>
            <li><a href="/vehicle/default/for/rent">Vehicle for rent</a></li>
            <li><a href="<?php echo $this -> rootUrl?>estate">Realestate</a></li>
            <li><a href="<?php echo $this -> rootUrl?>landlots">Land lots</a></li>
            <li class="last"><a href="<?php echo $this -> rootUrl?>mobile">Mobile</a></li>
        </ul>
    </div>
</div>
<div class="subNav">
	<div class="subNavCon">
    	<ul>
        	<li class="first"><a href="#">Rent your home</a></li>
            <li><a href="#">House</a></li>
            <li><a href="#">Rent your can</a></li>
            <li class="last"><a href="<?php echo $this -> rootUrl?>mobile">Mobile</a></li>
        </ul>
    </div>
</div>