<script type="text/javascript">
	$(document).ready(function(){
		$("#subNavCon-1").css("visibility", "visible").show();
		$(".navCon ul li").hover(function () {
			$(".subNavCon").css("visibility", "hidden").hide();
			$("#subNavCon-"+this.id).css("visibility", "visible").show();
		});
	});	
</script>
<div class="nav" style="overflow:hidden">
	<div class="navCon">
		<ul>
			<?php 
				$i = 1;
				$count = count($this->menuList['main_menu']); 
				foreach ( $this->menuList['main_menu'] as $key => $value) {
					if ( $value['parent_id'] == 0 ) {
						$first = ($i == 1) ? 'class="first"' : ''; 
						$last  = ($i == $count) ? 'class="last"' : '';
					
						echo '<li '.$first.$last.' id="'. $value['id'] .'"><a href="' . $this -> rootUrl . $value['link'] . '">' . $value['label'] . '</a></li>';
						$i++;
					}
				}
			?>
        </ul>
    </div>
</div>
<div class="subNav">
	<?php 
		$d = 0;
		//echo $count = count($this->menuList['main_menu']); exit; 
		foreach ( $this->menuList['main_menu'] as $main_key => $tree) {
			//print_r($value);
			if ( (isset($tree['tree'])) AND (is_array($tree['tree'])) AND (!empty($tree['tree']) ) ) {
				
				$count_tree = count($tree['tree']);
				$hidden_tree = ($d != 0) ? 'hidden' : ''; 
				echo '<div id="subNavCon-' . $tree['id'] . '" class="subNavCon '.$hidden_tree.'">
					<ul>';
			
				$j = 1;	
				foreach ($tree['tree'] as $sub_key => $value) {
					$first_tree = ($j == 1) ? 'class="first"' : ''; 
					$last_tree  = ($j == $count_tree) ? ' class="last"' : '';
					
					if (1 == $count_tree) {
						echo '<li class="first last" id="'. $value['id'] .'"><a href="' . $this -> rootUrl . $value['link'] . '">' . $value['label'] . '</a></li>';
					} else {
						echo '<li '.$first_tree.$last_tree.' id="'. $value['id'] .'"><a href="' . $this -> rootUrl . $value['link'] . '">' . $value['label'] . '</a></li>';
					}
					$j++;
				}
				
				echo '
				</ul>
				</div>
				';
				$d++;
			}
		}
	?>
</div>