<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './header/meta.phtml'; ?>
<link href="<?php print $this->defaultSkinCssUrl; ?>keyboard.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" >
var KEYBOARD_ICON = '<?php print $this->defaultSkinImagesUrl; ?>keyboard.gif';
function icon(symbol){
	var oldVal = $("#contentComment").val();
	$("#contentComment").val(oldVal + ' ' + symbol + ' ');
	return;
}
</script>
<script type="text/javascript" src="<?php print $this->defaultSkinJsUrl; ?>keyboard.js"></script>
<script type="text/javascript" src="<?php print $this->defaultSkinJsUrl; ?>swfobject.js"></script>
</head>
<body>
<!--header-->
<!--logoarea-->
		<?php include './header/logo.phtml';?>
<!--end logoarea-->
<!--end header-->
<!--containcont-->
<div class="containcont">
	<!--containrit-->
	<div class="containrit">
        <!--container-->
        <div class="container cleaner">
        	<!--data-->
            <div class="data cleaner">
                <!--tree-->
                <ul class="tree cleaner">
                    <li><a href="/">الصفحة الرئيسية</a></li>
		            <li><a href="/object-video/list/category/<?php echo $this->categoryDetails['id']; ?>"><?php echo $this->categoryDetails['title']; ?></a></li>
                    <li><?php echo $this->cleanHtml ( $this->videoDetails['title'] ); ?></li>
                </ul>
                <!--end tree-->
                <!--boxwite-->
                <div class="boxwite">
                    <span class="boxwtop"><span><em></em></span></span>
                    <div class="boxwdata">
                        <!--artcl-->
                        <div class="artcl">
                        	<h2 class="title">
                                <span class="titleiner"><?php echo $this->cleanHtml ( $this->videoDetails['title'] );?></span>
                                <p class="date"><?php echo  $this->videoDetails['date_added'] ;?></p>
                            </h2>
                            <div class="cleaner">
                                <div id="description">
                            		<p><?php echo $this->cleanHtml ( $this->videoDetails['intro_text'] ); ?></p>
                                </div>
                        <!--end artcl-->
                        <!-- video object -->
			                <?php if(isset($this->videoDetails['videoUrl']) and !empty($this->videoDetails['videoUrl'])) { ?>
							<br />
							<div class="interactiv cleaner" id="preview" style="text-align: center;">
							&nbsp;
							</div>
							<br />
			                <script type='text/javascript'>
								var s1 = new SWFObject('<?php print $this->defaultSkinImagesUrl; ?>player.swf',
										'player','480','385','9');
								s1.addParam('allowfullscreen','true');
								s1.addParam('allowscriptaccess','always');
								s1.addParam('flashvars','file=<?php echo $this->videoDetails['videoUrl']; ?>');
								s1.write('preview');
							</script>
							<?php } ?>
			                <!-- end video object -->
			                <!-- youtube object -->
			                <?php if(!empty($this->youtube)) { ?>
			                <center>
			                <div class="interactiv cleaner" id="preview">
			                	<center>
			                	<object width="480" height="385"><param name="movie" value="http://www.youtube.com/v/<?php echo $this->youtube; ?>&hl=en_US&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/<?php echo $this->youtube; ?>&hl=en_US&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="480" height="385"></embed></object>
			                	</center>
			                </div>
							<br />
			                <?php } ?>
              		  <!-- end youtube object -->
              		    <!--addcom-->
                                <div class="addcom cleaner">
                                    <!-- <a href="javascript:popUp('/object-video/tell-friend/id/<?php echo $this->videoDetails['id']; ?>','800','550')" class="tellfrnd">أخبر صديق</a> -->
                                    <a class="add-fav" onclick="javascript:bookMark();" href="javascript:void(0);">أضف إلى المفضلة</a>
                                </div>
                        <!--end addcom-->
                        <!--visitors comments-->
								<?php 
								if (is_array($this->commentList ) && !empty($this->commentList )) {
									include './object/comment/list.phtml'; 
								}
								?>
                        <!--end visitors comments-->
                        <!--add comment-->
                             <?php if ($this->allowComments == 1) { include './object/comment/add.phtml'; } ?>
                        <!--end add comment-->
                            </div>
                        </div>
                    </div>
                    <span class="boxwbotom"><span><em></em></span></span>
                </div>
                <!--end boxwite-->
            </div>
            <!--end data-->
            <!--lftpanel-->
            <div class="lftpanel">
            	<!--mutashabehat block-->
						<?php include './blocks/mutashabehat.phtml'; ?>
                    <!--end mutashabehat block-->
                    <!--dabt block-->
                    	<?php include './blocks/dabt.phtml'; ?>
                    <!--end dabt block-->    
                <!--Quraan block-->
					<?php include './blocks/quraan.phtml'; ?>
                <!--end Quraan block-->
                <!--musharakat block-->
					<?php include './blocks/musharakat.phtml'; ?>
                <!--end musharakat block-->
            </div>
            <!--end lftpanel-->
        </div>
        <!--end container-->
    </div>
    <!--end containrit-->
</div>
<!--end containcont-->
<!-- footer -->
<?php include './footer/footer.phtml'; ?>
<!-- end footer -->
</body>
</html>