<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
include './html/meta.phtml';
?>
</head>
<body>
<!--container-->
<div class="container">
<?php
include './html/header.phtml';
?>
<?php

include './html/menu.phtml';
?>
<?php

include './html/notification.phtml';
?>
<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<div class="lftnav">
<h3 class="margb1"><?php
echo $this->__ ( 'Category_Category' );
?></h3>
<ul>
	<li class="tab active" title="conttab1"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Category_Information' );
	?></span></a></li>
	<li class="tab" title="conttab2"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Category_Advanced' );
	?></span></a></li>
	<li class="tab" title="conttab3"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Category_Meta Data' );
	?></span></a></li>
</ul>
</div>
<!--end lftnav--> <!--ritcont-->
<form method="post" action="">
<div class="ritcont"><!--srch-rslt-->
<div class="srch-rslt">
<h3 class="fl pagetitle margthaf"><?php
echo $this->__ ( 'Category_Add New Category' );
?></h3>
<a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="-1" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Category_Save And Continue Edit' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="1" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Category_Save' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="2" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Category_Reset' );
?></button>
</em></a> <a href="javascript:void(0);" class="backbtn"><em>
<button name="btn_submit" value="3" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Category_Back' );
?></button>
</em></a></div>
<!--end srch-rslt--> <!--conttab1-->
<div class="mytabscont" id="conttab1" style="display: block"><!--entrdata-->
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Category_Information' );
?></h2>
<div class="entrdcont">
<div class="wdthauto"><input type="hidden" id="Id" name="Id"
	value="<?php
	print $this->sanitized->Id->value;
	?>" /> <input
	type="hidden" id="token" name="token"
	value="<?php
	print $this->sanitized->token->value;
	?>" />
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Title' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			name="title" id="title"
			value="<?php
			echo $this->sanitized->title->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->title->errorMessageStyle;
		?>"><?php
		print $this->sanitized->title->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Label' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="label" name="label"
			value="<?php
			print $this->sanitized->label->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->label->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->label->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Description' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="description" name="description"
			value="<?php
			print $this->sanitized->description->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->description->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->description->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Type' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct" id="type"
			name="type">
	<?php
	echo $this->categoryTypeList;
	?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->type->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->type->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Parent' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct" id="parent"
			name="parent">
	<?php
	echo $this->parentList;
	?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->parent->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->parent->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop">&nbsp;</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="checkbox" class="intchk fl"
				id="showInMenu" name="showInMenu" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->showInMenu->value) ? 'checked="checked"' : '';
				?> />
			<label for="showInList" class="inptlabl fl"><?php
			echo $this->__ ( 'Category_Show in Menu' );
			?></label>
			<div class="validat" style="<?php
			print $this->sanitized->showInMenu->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->showInMenu->errorMessage;
		?></div>
			</li>
			<li class="cleaner"><input type="checkbox" class="intchk fl"
				id="published" name="published" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->published->value) ? 'checked="checked"' : '';
				?> />
			<label for="published" class="inptlabl fl"><?php
			echo $this->__ ( 'Category_Published' );
			?></label>
			<div class="validat" style="<?php
			print $this->sanitized->published->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->published->errorMessage;
		?></div>
			</li>
			<li class="cleaner"><input type="checkbox" id="approved"
				class="intchk fl" name="approved" value="Yes"
				<?php
				echo ('Yes' == $this->sanitized->approved->value) ? 'checked="checked"' : '';
				?> />
			<label for="approved" class="inptlabl fl"><?php
			echo $this->__ ( 'Category_Approved' );
			?></label>
			<div class="validat" style="<?php
			print $this->sanitized->approved->errorMessageStyle;
			?>">
		<?php
		print $this->sanitized->approved->errorMessage;
		?></div>
			</li>
		</ul>
		</td>
	</tr>
	<?php
	if (! empty ( $this->afterIdList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Order' );
		?>:</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="radio" id="order" class="intchk fl"
				name="order" value="0"
				<?php
		echo (0 == $this->sanitized->order->value) ? 'checked="checked"' : '';
		?> />
			<label for="order" class="inptlabl fl"><?php
		echo $this->__ ( 'Category_At the beginning of the list' );
		?></label><br />
			<div class="validat" style="<?php
		print $this->sanitized->order->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->order->errorMessage;
		?></div>
			</li>
			<li class="cleaner"><input type="radio" id="order" class="intchk fl"
				name="order" value="-1"
				<?php
		echo (- 1 == $this->sanitized->order->value) ? 'checked="checked"' : '';
		?> />
			<label for="after" class="inptlabl fl"><?php
		echo $this->__ ( 'Category_After' );
		?></label><br />
			<select class="inptslct" id="afterId" name="afterId">
		<?php
		echo $this->afterIdList;
		?>
		</select>
			<div class="validat" style="<?php
		print $this->sanitized->afterId->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->afterId->errorMessage;
		?></div>
			</li>
		</ul>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="order" value="0" /></td>
	</tr>
	<?php
	}
	?>
</table>
</div>
</div>
</div>
<!--end entrdata--></div>
<!--end conttab1--> <!--conttab2-->
<div class="mytabscont" id="conttab2" style="display: none">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Category_Advanced Settings' );
?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Comments' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="comment" name="comment"
			value="<?php
			print $this->sanitized->comment->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->comment->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->comment->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Options' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="option" name="option"
			value="<?php
			print $this->sanitized->option->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->option->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->option->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Publish From' );
		?>:</td>
		<td class="lablvalue jstalgntop">
		<div class="calen_beside"><input type="text"
			class="inpttxt wdth70 slctdate" id="slct_date2" name="publishFrom"
			value="<?php
			print $this->sanitized->publishFrom->value;
			?>" /></div>
		<div class="validat" style="<?php
		print $this->sanitized->publishFrom->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->publishFrom->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Publish To' );
		?>:</td>
		<td class="lablvalue jstalgntop">
		<div class="calen_beside"><input type="text"
			class="inpttxt wdth70 slctdate" id="slct_date3" name="publishTo"
			value="<?php
			print $this->sanitized->publishTo->value;
			?>" /></div>
		<div class="validat" style="<?php
		print $this->sanitized->publishTo->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->publishTo->errorMessage;
		?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
<!--end entrdata--></div>
<!--end conttab2--> <!--conttab3-->
<div class="mytabscont" id="conttab3" style="display: none">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Category_Meta' );
?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Page Title' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="pageTitle" name="pageTitle"
			value="<?php
			print $this->sanitized->pageTitle->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->pageTitle->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->pageTitle->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Meta Title' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="metaTitle" name="metaTitle"
			value="<?php
			print $this->sanitized->metaTitle->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->metaTitle->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->metaTitle->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Meta Keywords' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="metaKey" name="metaKey"
			value="<?php
			print $this->sanitized->metaKey->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->metaKey->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->metaKey->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Meta Description' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="metaDesc" name="metaDesc"
			value="<?php
			print $this->sanitized->metaDesc->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->metaDesc->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->metaDesc->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Category_Meta Data' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="metaData" name="metaData"
			value="<?php
			print $this->sanitized->metaData->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->metaData->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->metaData->errorMessage;
		?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
</div>
<!--end conttab3--> <!--end ritcont--></div>
</form>
</div>
<!--end maincont--></div>
<!--end content-->

<?php
include './html/footer.phtml';
?>

</div>
<!--end container-->
</body>
</html>