
<div class="ritpanel"><!--mutashabehat block-->
						<?php
						include './blocks/mutashabehat.phtml';
						?>
                    <!--end mutashabehat block--> <!--dabt block-->
                    	<?php
																					include './blocks/dabt.phtml';
																					?>
                    <!--end dabt block--> <!--voting-->
						<?php
						include './blocks/voting.phtml';
						?>
                    <!--end voting--></div>