      <div class="ritPan">
    	<!--newsletter block-->
			<?php include './blocks/newsletter.phtml'; ?>
        <!--end newsletter block-->

        <div>
        	<!--facebook block-->
			<?php include './blocks/facebook.phtml'; ?>
        	<!--end facebook block-->
        	
        	<!--right banners block-->
			<?php include './banner/rightBanners.phtml'; ?>
        	<!--end right banners block-->
        </div>

      </div>
      <div class="cls"></div>