            <div>
       	    <h2 title="Vehicle Bank Loan of BMW - 225i 2005">Land Losts Bank Loan</h2>
                <div class="box">
                	<div>
                    	<div class=" insuranceLogo"><img height="30" width="84" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_bank.png"></div>
                        <div class=" insuranceName">QNB Qatar Bank</div>
                        <div class="nxt-back">
                        	<div class="btnNxt"></div>
                            <div class="btnbackInActive"></div>
                            <div class="cls"></div>
                        </div>
                        <div class="cls"></div>
                  </div>
                  <div class="dataListSmall">
           	  <div>
                    	<div class="ttl"><label for="amount">Loan amount:</label></div>
                        <div class="data"><input type="text" id="amount" class="txtInputMidd"></div>
                        <div class="cls"></div>
                    </div>
                    <div>
                    	<div class="ttl"><label for="payment">Down payment:</label></div>
                        <div class="data"><input type="text" id="payment" class="txtInputMidd"></div>
                        <div class="cls"></div>
                    </div>
                    <div>
                    	<div class="ttl"><label for="period">Grce period:</label></div>
                        <div class="data"><input type="text" id="period" class="txtInputMidd"></div>
                        <div class="cls"></div>
                    </div>
                    <div>
                    	<div class="ttl">
           	      <label for="tenure">Loan tenure:</label></div>
                        <div class="data"><input type="text" id="tenure" class="txtInputMidd"></div>
                        <div class="cls"></div>
                    </div>
              </div>
                    <div>
                    	<input type="button" value="Result" class="btn">
                    </div>
                    
           	  </div>
        </div>