<!--                	<div class="box">
                    	<h2 class="boxtitle"><span><img src="<?php
																					print $this->defaultSkinImagesUrl;
																					?>title2.gif" alt="الضبط بالتقعيد" width="97" height="16" /></span></h2>
                        <div class="boxdata">
                        	<ul class="lst">
                            	<li><span class="circlbg"><a href="#er">استعرض الكتاب</a></span></li>
                                <li><span class="circlbg"><a href="#er">حمّل الكتاب</a></span></li>
                                <li><span class="circlbg"><a href="/object-file/list/category/30">الكتاب بلغات أخرى</a></span></li>
                                <li><span class="circlbg"><a href="#er">الكتاب بالباوربوينت</a></span></li>
                                <li><span class="circlbg"><a href="#er">تلخيص الكتاب</a></span></li>
                            </ul>
                        </div>
                        <span class="boxbotom"><span></span></span>
                    </div>-->
<div class="box">
<h2 class="boxtitle"><span><img
	src="<?php
	print $this->defaultSkinImagesUrl;
	?>title2.gif"
	alt="الضبط بالتقعيد" width="97" height="16" /></span></h2>
<div class="boxdata">
<ul class="lst">
                            <?php
																												$this->drawMenu ( $this->menuList ['dabt'] );
																												?>
				        </ul>
</div>
<span class="boxbotom"><span></span></span></div>