        <div>
        	<h3>Featured realestate</h3>
            <div>
<div class="hfBox">
                	<div><img src="<?php echo $this->defaultSkinImagesUrl ?>sample_cars.png" width="150" height="100" alt="" /></div>
                    <div>Mercedes-Benz
                      <br />
                      C63 AMG<br />
                      Personal 
<span class="num">$385.00</span></div>
					<div class="more"><a href="#more"><img src="<?php echo $this->defaultSkinImagesUrl ?>spacer.gif" width="70" height="26" alt="" /></a></div>
              </div>
                <div class="hfBox">
                	<div><img src="<?php echo $this->defaultSkinImagesUrl ?>sample_cars.png" width="150" height="100" alt="" /></div>
                    <div>Mercedes-Benz
                      <br />
                      C63 AMG<br />
                      Personal 
<span class="num">$385.00</span></div>
					<div class="more"><a href="#more"><img src="<?php echo $this->defaultSkinImagesUrl ?>spacer.gif" width="70" height="26" alt="" /></a></div>
                </div>
                <div class="hfBox">
                	<div><img src="<?php echo $this->defaultSkinImagesUrl ?>sample_cars.png" width="150" height="100" alt="" /></div>
                    <div>Mercedes-Benz
                      <br />
                      C63 AMG<br />
                      Personal 
<span class="num">$385.00</span></div>
					<div class="more"><a href="#more"><img src="<?php echo $this->defaultSkinImagesUrl ?>spacer.gif" width="70" height="26" alt="" /></a></div>
                </div>
                <div class="hfBox lastDiv">
                	<div><img src="<?php echo $this->defaultSkinImagesUrl ?>sample_cars.png" width="150" height="100" alt="" /></div>
                    <div>Mercedes-Benz
                      <br />
                      C63 AMG<br />
                      Personal 
<span class="num">$385.00</span></div>
					<div class="more"><a href="#more"><img src="<?php echo $this->defaultSkinImagesUrl ?>spacer.gif" width="70" height="26" alt="" /></a></div>
                </div>
                <div class="cls"></div>
            </div>
        </div>