			<div>
           	  <h2 title="Vehicle Insurance of BMW - 225i 2005">Vehicle Insurance</h2>
            <div class="box">
                	<div>
                    	<div class=" insuranceLogo"><img height="28" width="72" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_insurance.png"></div>
                      <div class=" insuranceName">Alico Qatar</div>
                  <div class="nxt-back">
                        	<div class="btnNxt"></div>
                            <div class="btnbackInActive"></div>
                            <div class="cls"></div>
                        </div>
                        <div class="cls"></div>
                    </div>
                    <div class="dataListSmall">
                   	  <div class="ttl"><label for="insType">Insurance type:</label></div>
                      <div class="data"><select id="insType"><option>Select</option></select></div>
                      <div class="cls"></div>
                    </div>
                    <div>
                   	  <input type="button" value="Result" class="btn">
                    </div>
          <div class="boxGray">
                    BMW - 225i 2005 - 8 Cylinders<br>
                    Full ensurance<br>
                    5 Years
                    </div>
               	</div>
            </div>