
<div class="box">
<h2 class="boxtitle"><span><img
	src="<?php
	print $this->defaultSkinImagesUrl;
	?>title3.gif"
	alt="مشاركات القراء " width="101" height="16" /></span></h2>
<div class="boxdata">
<ul class="lst">
	<li><span class="circlbg"><a href="#er">شاركنا (أضف قاعدة – مثالا )</a></span></li>
	<li><span class="circlbg"><a href="#er">إسأل في الآيات المتشابهة</a></span></li>
	<li><span class="circlbg"><a href="#er">مقترحات وملحوظات</a></span></li>
</ul>
</div>
<span class="boxbotom"><span></span></span></div>