<!--                	<div class="box">
                    	<h2 class="boxtitle"><span><img src="<?php
																					print $this->defaultSkinImagesUrl;
																					?>title1.gif" alt="المتشابهات" width="78" height="16" /></span></h2>
                        <div class="boxdata">
                        	<ul class="lst">
                            	<li><span class="circlbg"><a href="#er">كتب (منظومات – مؤلفات )</a></span></li>
                                <li><span class="circlbg"><a href="/object-video/list/category/29">مرئيات</a></span></li>
                                <li><span class="circlbg"><a href="#er">صوتيات</a></span></li>
                                <li><span class="circlbg"><a href="#er">مواقع</a></span></li>
                                <li><span class="circlbg"><a href="/object-article/list/category/28">استعرض الآيات المتشابهة</a></span></li>
                                <li><span class="circlbg"><a href="#er">مواضيع مميزة</a></span></li>
                            </ul>
                        </div>
                        <span class="boxbotom"><span></span></span>
                    </div>-->
<div class="box">
<h2 class="boxtitle"><span><img
	src="<?php
	print $this->defaultSkinImagesUrl;
	?>title1.gif"
	alt="المتشابهات" width="78" height="16" /></span></h2>
<div class="boxdata">
<ul class="lst">
                            <?php
																												$this->drawMenu ( $this->menuList ['mutashbehat'] );
																												?>
				        </ul>
</div>
<span class="boxbotom"><span></span></span></div>