      	<form action="" method="post">
      	<div class="newsletter">
        	<div><label>Sign up for our newsletter</label></div>
       	  <div>
                <input type="submit" class="btn" value="Subscribe" id="submitEmail" />
            <input class="field" type="text" id="email" name="email" title="Your email" />
                <div class="cls"></div>
        	</div>
        </div>
        </form>