		<div>
        	<div class="sendBox">
            	<div class="sendIcon"><a href="#">Email to a friend</a></div>
              <div class="commentIcon"><a href="#">Post a comment</a></div>
                <div class="compareIcon"><a href="#">Add to compare</a></div>
            </div>
            <div class="socialBox"><img height="71" width="176" src="<?php echo $this->defaultSkinImagesUrl?>sample_social.png" alt=""></div>
            <div class="cls"></div>
        </div>