                    <div class="boxwite">
                    	<span class="boxwtop"><span><em></em></span></span>
                        <div class="boxwdata">
                        	<p class="margbhaf"><img src="<?php print $this->defaultSkinImagesUrl; ?>votetitle.gif" alt="تصويت" width="45" height="14" /></p>
                            <strong>ما هو رأيك بكتابنا الضبط بالتقعيد للمتشابه اللفظي في القرآن المجيد</strong>
                            <ul class="votelst">
                            	<li class="cleaner">
                                	<input type="radio" class="inptrdio fr" id="option1" name="voteopt" />
                                    <label class="inptlabl fr" for="option1">ممتاز جدا</label>
                                </li>
                                <li class="cleaner">
                                	<input type="radio" class="inptrdio fr" id="option2" name="voteopt" />
                                    <label class="inptlabl fr" for="option2">ممتاز</label>
                                </li>
                                <li class="cleaner">
                                	<input type="radio" class="inptrdio fr" id="option3" name="voteopt" />
                                    <label class="inptlabl fr" for="option3">جيد</label>
                                </li>
                                <li class="cleaner">
                                	<input type="radio" class="inptrdio fr" id="option4" name="voteopt" />
                                    <label class="inptlabl fr" for="option4">سيء</label>
                                </li>
                            </ul>
                            <ul class="voteresult" style="display:none">
                            	<li class="cleaner">
                                    <p>ممتاز جدا <strong class="red">40%</strong></p>
                                    <div class="votebar">
                                    	<span style="width:40%"></span>
                                    </div>
                                </li>
                                <li class="cleaner">
                                    <p>ممتاز <strong class="red">20%</strong></p>
                                    <div class="votebar">
                                    	<span style="width:20%"></span>
                                    </div>
                                </li>
                                <li class="cleaner">
                                    <p>جيد <strong class="red">15%</strong></p>
                                    <div class="votebar">
                                    	<span style="width:15%"></span>
                                    </div>
                                </li>
                                <li class="cleaner">
                                    <p>سيء <strong class="red">15%</strong></p>
                                    <div class="votebar">
                                    	<span style="width:15%"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <span class="boxwbotom"><span><em></em></span></span>
                    </div>