<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './header/meta.phtml'; ?>
</head>
<body>
<div class="ramadanpatrn">
<div class="ramadanrit">
<!--containcont-->
<div class="containcont">
    <!--container-->
    <div class="container">
		<!--logoarea-->
		<?php include './header/logo.phtml';?>
		<!--end logoarea-->
        <!--mainnav-->
        <?php include './header/topMenu.phtml'; ?>
        <!--end mainnav-->
        <!--stats-->
        <?php include './header/status.phtml'; ?>
        <!--end stats-->
        <!--ticker-->
		<?php include './header/ticker.phtml'; ?>
        <!--end ticker-->
        <!--Breaknews ticker-->
        <?php include './header/Breaknews-ticker.phtml'; ?>
        <!--end Breaknews ticker-->
        <!--content-->
        <div class="content cleaner">
        
        	<div class="contrit">
            	<!--tree-->
                <ul class="tree cleaner">
                    <li><a href="/">الصفحة الرئيسية</a></li>
                    <li>شكراً لمشاركتكم</li>
                </ul>
                <!--end tree-->
                <div class="algnmid margt2">
	        		<h3 class="red margb1">شكرأ لمشاركتكم،
	        		لقد تم إرسال مشاركتكم بنجاح.
	        		</h3>
	        	</div>
		        <!--end content-->
                <?php include './banner/centerBanner.phtml'; ?>
            </div>
            <!--end contrit-->
            <!--lftpanel-->
			<?php include './object/leftColumn.phtml'; ?>
            <!--end lftpanel-->
        </div>
        <!--end content-->
    </div>
    <!--end container-->
</div>
<!--end containcont-->
<!--footer-->
<?php include './footer/footer.phtml'; ?>
<!--end footer-->
</div>
</div>
</body>
</html>