						<div class="fannbox">
                            <h3 class="domentitle">
                                <span><a href="/object-article/list/category/<?php echo NEWS_ENTERTAINMENT; ?>" class="fann"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="أخبار فنية" title="أخبار فنية" width="79" height="22" /></a></span>
                            </h3>
                            <div class="domendata">
                            	<ul class="newslst2 cleaner">
									<?php
									$countEntertainment = count($this->newsEntertainmentList);
									for($k=0; $k< $countEntertainment; $k++ ){ 
									?>
                                    <li>
                                        <p class="algnmid"><a href="/object-article/view/id/<?php echo $this->newsEntertainmentList[$k]['id']; ?>/title/<?php echo $this->newsEntertainmentList[$k]['title'];?>"><img src="<?php echo $this->newsEntertainmentList[$k]['imageUrl']; ?>" alt="<?php echo $this->newsEntertainmentList[$k]['photo_alias']; ?>" class="thumb" title="<?php echo $this->newsEntertainmentList[$k]['photo_alias'];  ?>"  /></a></p>
                                        <p><a href="/object-article/view/id/<?php echo $this->newsEntertainmentList[$k]['id']; ?>/title/<?php echo $this->newsEntertainmentList[$k]['title']; ?>"><?php echo $this->cleanHtml ( $this->newsEntertainmentList[$k]['title'] ); ?></a></p>
                                    </li>
                                    <?php } ?>
                                </ul>
                        		<p class="morelnk"><a href="/object-article/list/category/<?php echo NEWS_ENTERTAINMENT; ?>" class="more">المزيد</a></p>
                            </div>
                        </div>