
<div class="jortoday margt1" style="margin-top: 0px;">
<h3 class="domentitle"><span><a
	href="/object-article/list/category/<?php
	echo NEWS_JORDAN_TODAY;
	?>"
	class="jortitle"><img
	src="<?php
	print $this->defaultSkinImagesUrl;
	?>spacer.gif"
	alt="الأردن اليوم" title="الأردن اليوم" width="94" height="21" /></a></span>
</h3>
<div class="domendata">
<ul class="newslstbg cleaner">
							<?php
							$countJordanToday = count ( $this->newsJordanTodayList );
							for($k = 0; $k < 8; $k ++) {
								?>
                            <li>
	<p class="algnmid"><a
		href="/object-article/view/id/<?php
								echo $this->newsJordanTodayList [$k] ['id'];
								?>/title/<?php
								echo $this->newsJordanTodayList [$k] ['title'];
								?>"><img
		src="<?php
								echo $this->newsJordanTodayList [$k] ['imageUrl'];
								?>"
		alt="<?php
								echo $this->newsJordanTodayList [$k] ['photo_alias'];
								?>"
		title="<?php
								echo $this->newsJordanTodayList [$k] ['photo_alias'];
								?>"
		class="thumb" /></a></p>
	<p class="descmin"><a
		href="/object-article/view/id/<?php
								echo $this->newsJordanTodayList [$k] ['id']?>/title/<?php
								echo $this->newsJordanTodayList [$k] ['title'];
								?>"><?php
								echo $this->cleanHtml ( $this->newsJordanTodayList [$k] ['title'] );
								?></a></p>
	<p>التعليقات: <strong class="red"><?php
								echo $this->newsJordanTodayList [$k] ['total_comments'];
								?></strong></p>
	<p>المشاهدات: <strong class="red"><?php
								echo $this->newsJordanTodayList [$k] ['total_views'];
								?></strong></p>
	</li>
                            <?php
							}
							?>
                        </ul>
<div class="localnews cleaner">
<ul class="locallst localrit">
	<li>
	<p class="margb3"><a
		href="/object-article/view/id/<?php
		echo $this->newsJordanTodayList [8] ['id']?>/title/<?php
		echo $this->newsJordanTodayList [8] ['title'];
		?>"
		class="blak fnt11"><strong><?php
		echo $this->cleanHtml ( $this->newsJordanTodayList [8] ['title'] );
		?></strong></a></p>
	<ul class="readnum cleaner">
		<li>المشاهدات: <strong class="red"><?php
		echo $this->newsJordanTodayList [8] ['total_views'];
		?></strong></li>
		<li class="last">التعليقات: <strong class="red"><?php
		echo $this->newsJordanTodayList [8] ['total_comments'];
		?></strong></li>
	</ul>
	</li>
	<li>
	<p class="margb3"><a
		href="/object-article/view/id/<?php
		echo $this->newsJordanTodayList [9] ['id']?>/title/<?php
		echo $this->newsJordanTodayList [9] ['title'];
		?>"
		class="blak fnt11"><strong><?php
		echo $this->cleanHtml ( $this->newsJordanTodayList [9] ['title'] );
		?></strong></a></p>
	<ul class="readnum cleaner">
		<li>المشاهدات: <strong class="red"><?php
		echo $this->newsJordanTodayList [9] ['total_views'];
		?></strong></li>
		<li class="last">التعليقات: <strong class="red"><?php
		echo $this->newsJordanTodayList [9] ['total_comments'];
		?></strong></li>
	</ul>
	</li>
	<li class="last">
	<p class="margb3"><a
		href="/object-article/view/id/<?php
		echo $this->newsJordanTodayList [10] ['id']?>/title/<?php
		echo $this->newsJordanTodayList [10] ['title'];
		?>"
		class="blak fnt11"><strong><?php
		echo $this->cleanHtml ( $this->newsJordanTodayList [10] ['title'] );
		?></strong></a></p>
	<ul class="readnum cleaner">
		<li>المشاهدات: <strong class="red"><?php
		echo $this->newsJordanTodayList [10] ['total_views'];
		?></strong></li>
		<li class="last">التعليقات: <strong class="red"><?php
		echo $this->newsJordanTodayList [10] ['total_comments'];
		?></strong></li>
	</ul>
	</li>
</ul>
<ul class="locallst locallft">
	<li>
	<p class="margb3"><a
		href="/object-article/view/id/<?php
		echo $this->newsJordanTodayList [11] ['id']?>/title/<?php
		echo $this->newsJordanTodayList [11] ['title'];
		?>"
		class="blak fnt11"><strong><?php
		echo $this->cleanHtml ( $this->newsJordanTodayList [11] ['title'] );
		?></strong></a></p>
	<ul class="readnum cleaner">
		<li>المشاهدات: <strong class="red"><?php
		echo $this->newsJordanTodayList [11] ['total_views'];
		?></strong></li>
		<li class="last">التعليقات: <strong class="red"><?php
		echo $this->newsJordanTodayList [11] ['total_comments'];
		?></strong></li>
	</ul>
	</li>
	<li>
	<p class="margb3"><a
		href="/object-article/view/id/<?php
		echo $this->newsJordanTodayList [12] ['id']?>/title/<?php
		echo $this->newsJordanTodayList [12] ['title'];
		?>"
		class="blak fnt11"><strong><?php
		echo $this->cleanHtml ( $this->newsJordanTodayList [12] ['title'] );
		?></strong></a></p>
	<ul class="readnum cleaner">
		<li>المشاهدات: <strong class="red"><?php
		echo $this->newsJordanTodayList [12] ['total_views'];
		?></strong></li>
		<li class="last">التعليقات: <strong class="red"><?php
		echo $this->newsJordanTodayList [12] ['total_comments'];
		?></strong></li>
	</ul>
	</li>
	<li class="last">
	<p class="margb3"><a
		href="/object-article/view/id/<?php
		echo $this->newsJordanTodayList [13] ['id']?>/title/<?php
		echo $this->newsJordanTodayList [13] ['title'];
		?>"
		class="blak fnt11"><strong><?php
		echo $this->cleanHtml ( $this->newsJordanTodayList [13] ['title'] );
		?></strong></a></p>
	<ul class="readnum cleaner">
		<li>المشاهدات: <strong class="red"><?php
		echo $this->newsJordanTodayList [13] ['total_views'];
		?></strong></li>
		<li class="last">التعليقات: <strong class="red"><?php
		echo $this->newsJordanTodayList [13] ['total_comments'];
		?></strong></li>
	</ul>
	</li>
</ul>
</div>
</div>
</div>