
<!--mainnav-->
<div class="mainnav">
<ul class="navlst cleaner">
	<li><a href="/admin/handle/pkg/category/action/add">Category</a>
	<ul>
		<li><a href="/admin/handle/pkg/category/action/add">Add Category</a></li>
		<li><a href="/admin/handle/pkg/category-type/action/add">Add Category Type</a></li>
		<li><a href="/admin/handle/pkg/category/action/list">List Categories</a></li>
		<li class="last"><a href="/admin/handle/pkg/category-type/action/list">List Categories Types</a></li>
	</ul>
	</li>
	<li><a href="/admin/handle/pkg/menu/action/add">Menu</a>
	<ul>
		<li><a href="/admin/handle/pkg/menu/action/add">Add Menu</a></li>
		<li><a href="/admin/handle/pkg/menu/action/list">List Menu</a></li>
		<li><a href="/admin/handle/pkg/menu-type/action/add">Add Menu Type</a></li>
		<li class="last"><a href="/admin/handle/pkg/menu-type/action/list">List Menu Type</a></li>
	</ul>
	</li>
	<li><a href="#">Object</a>
	<ul>
		<li><a class="hassub" href="#">Add Object</a>
		<ul>
				<li><a href="/admin/handle/pkg/object-article/action/add">Add Article</a></li>
				<li><a href="/admin/handle/pkg/object-photo/action/add">Add Photo</a></li>
				<li><a href="/admin/handle/pkg/object-static/action/add">Add Static Page</a></li>
				<li><a href="/admin/handle/pkg/object-abuse/action/add">Add Abuse</a></li>
				<li><a href="/admin/handle/pkg/object-abuse-type/action/add">Add Abuse Type</a></li>
				<li><a href="/admin/handle/pkg/object-directory/action/add">Add Folder</a></li>
				<li><a href="/admin/handle/pkg/object-file/action/add">Add File</a></li>
		</ul>
		</li>
		<li><a class="hassub" href="#">List Object</a>
		<ul>
				<li><a href="/admin/handle/pkg/object-article/action/list">List Articles</a></li>
				<li><a href="/admin/handle/pkg/object-photo/action/list">List Photos</a></li>
				<li><a href="/admin/handle/pkg/object-static/action/list">List Static Pages</a></li>
				<li><a href="/admin/handle/pkg/object-abuse/action/list">List Abuse</a></li>
				<li><a href="/admin/handle/pkg/object-abuse-type/action/list">List Abuse Types</a></li>
				<li><a href="/admin/handle/pkg/object-directory/action/list">List Folders</a></li>
				<li><a href="/admin/handle/pkg/object-file/action/list">List Files</a></li>
		</ul>
		</li>
		<li><a href="/admin/handle/pkg/object-source/action/add">Add Source</a></li>
		<li class="last"><a href="/admin/handle/pkg/object-source/action/list">List Sources</a></li>
	</ul>
	</li>
	<li><a href="/admin/handle/pkg/tag/action/add">Tag</a>
	<ul>
		<li><a href="/admin/handle/pkg/tag/action/add">Add Tag</a></li>
		<li><a href="/admin/handle/pkg/tag/action/addBlackTag">Add Black Tag</a></li>
		<li><a href="/admin/handle/pkg/tag/action/list">List Tag</a></li>
		<li class="last"><a href="/admin/handle/pkg/tag/action/blackList">Black List Keywords</a></li>
	</ul>
	</li>
	<li><a href="/admin/handle/pkg/live/action/edit">Live Streaming</a>
	<li class="visitors"><strong>Number of Visitors <span class="orng">(801)</span></strong></li>
</ul>
</div>
<!--end mainnav-->