<?php if (1 != $this->userLevel) { ?>
<!--mainnav-->
<div class="mainnav">
<ul class="navlst cleaner">
	<li><a href="/admin">الرئيسية</a></li>
</ul>
</div>
<!--end mainnav-->
<?php 
} else { ?>
<!--mainnav-->
<div class="mainnav">
<ul class="navlst cleaner">
	<li><a href="/admin">الرئيسية</a>
	<li><a href="/admin/handle/pkg/menu/action/add">القوائم</a>
	<ul>
		<li><a href="/admin/handle/pkg/menu/action/add">إضافة قائمة</a></li>
		<li><a href="/admin/handle/pkg/menu/action/list">عرض القوائم</a></li>
		<li><a href="/admin/handle/pkg/menu-type/action/add">إضافة نوع قوائم جديد</a></li>
		<li class="last"><a href="/admin/handle/pkg/menu-type/action/list">عرض أنواع القوائم</a></li>
	</ul>
	</li>
	<li><a href="/admin/handle/pkg/category/action/add">التصنيفات</a>
	<ul>
		<li><a href="/admin/handle/pkg/category/action/add">إضافة تصنيف</a></li>
		<li><a href="/admin/handle/pkg/category-type/action/add">إضافة نوع تصنيف جديد</a></li>
		<li><a href="/admin/handle/pkg/category/action/list">قائمة التصنيفات</a></li>
		<li class="last"><a href="/admin/handle/pkg/category-type/action/list">قائمة أنواع التصنيفات</a></li>
	</ul>
	</li>
	<li><a href="#">المواضيع</a>
	<ul>
		<li><a class="hassub" href="#">إضافة موضوع جديد</a>
		<ul>
				<li><a href="/admin/handle/pkg/object-article/action/add">إضافة مقالة</a></li>
				<li><a href="/admin/handle/pkg/object-photo/action/add">إضافة صورة</a></li>
				<li><a href="/admin/handle/pkg/object-video/action/add">إضافة فيديو</a></li>
				<li><a href="/admin/handle/pkg/object-static/action/add">إضافة صفحة للموقع</a></li>
				<li><a href="/admin/handle/pkg/object-directory/action/add">إنشاء مجلد</a></li>
				<li><a href="/admin/handle/pkg/object-file/action/add">تحميل ملف</a></li>
				<li><a href="/admin/handle/pkg/object-source/action/add">إضافة مصدر</a></li>
				<li class="last"><a href="/admin/handle/pkg/object-url/action/add">إضافة رابط</a></li>
		</ul>
		</li>
		<li><a class="hassub" href="#">عرض المواضيع</a>
			<ul>
				<li><a href="/admin/handle/pkg/object-article/action/list">عرض المقالات</a></li>
				<li><a href="/admin/handle/pkg/object-photo/action/list">عرض الصور</a></li>
				<li><a href="/admin/handle/pkg/object-video/action/list">عرض الفيديو</a></li>
				<li><a href="/admin/handle/pkg/object-static/action/list">عرض صفحات الموقع</a></li>
				<li><a href="/admin/handle/pkg/object-directory/action/list">عرض المجلدات</a></li>
				<li><a href="/admin/handle/pkg/object-file/action/list">عرض الملفات</a></li>
				<li><a href="/admin/handle/pkg/object-source/action/list">عرض المصادر</a></li>
				<li class="last"><a href="/admin/handle/pkg/object-url/action/list">عرض الروابط</a></li>
			</ul>
		</li>
		<li><a href="/admin/handle/pkg/feature/action/list">عرض مقالات مهمة</a></li>
		<li class="last"><a href="/admin/handle/pkg/object-comment/action/list">عرض التعليقات</a></li>
	</ul>
	</li>
	<li><a href="/admin/handle/pkg/poll/action/add">الاستطلاعات</a>
		<ul>
			<li><a href="/admin/handle/pkg/poll/action/add">إضافة استطلاع</a></li>
			<li class="last"><a href="/admin/handle/pkg/poll/action/list">عرض الاستطلاعات</a></li>
		</ul>
	</li>
	<li><a href="#">الأراضي</a>
		<ul>
			<li><a href="#">إضافة أرض</a></li>
			<li><a href="#">عرض الأراضي</a></li>
			<li class="last"><a href="#" class="hassub">عرض القوائم الفرعية</a>
				<ul>
					<li><a href="/admin/handle/pkg/landlots-ancillary-buildings/action/list">المباني الملحقة</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear1/action/list">Live near 1</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear2/action/list">Live near 2</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear3/action/list">Live near 3</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear4/action/list">Live near 4</a></li>
					<li><a href="/admin/handle/pkg/landlots-for/action/list">For</a></li>
					<li><a href="/admin/handle/pkg/landlots-provence/action/list">provence</a></li>
					<li><a href="/admin/handle/pkg/landlots-location/action/list">الموقع</a></li>
					<li class="last"><a href="/admin/handle/pkg/landlots-type/action/list">النوع</a></li>
				</ul>
			</li>
			<li class="last"><a href="#" class="hassub">إضافة إلى القوائم الفرعية</a>
				<ul>
					<li><a href="/admin/handle/pkg/landlots-ancillary-buildings/action/add">المباني الملحقة</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear1/action/add">Live near 1</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear2/action/add">Live near 2</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear3/action/add">Live near 3</a></li>
					<li><a href="/admin/handle/pkg/landlots-livenear4/action/add">Live near 4</a></li>
					<li><a href="/admin/handle/pkg/landlots-for/action/add">For</a></li>
					<li><a href="/admin/handle/pkg/landlots-provence/action/add">provence</a></li>
					<li><a href="/admin/handle/pkg/landlots-location/action/add">الموقع</a></li>
					<li class="last"><a href="/admin/handle/pkg/landlots-type/action/add">النوع</a></li>
				</ul>
			</li>
		</ul>
	</li>
	<li><a href="#">العقارات</a>
		<ul>
			<li><a href="#">إضافة عقار</a></li>
			<li><a href="#">عرض العقارات</a></li>
			<li class="last"><a href="#" class="hassub">عرض القوائم الفرعية</a>
				<ul>
					<li><a href="/admin/handle/pkg/estate-air-condition/action/list">التدفئة المركزية</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear1/action/list">Live near 1</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear2/action/list">Live near 2</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear3/action/list">Live near 3</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear4/action/list">Live near 4</a></li>
					<li><a href="/admin/handle/pkg/estate-outdoor-amenities/action/list">Outdoor amenities</a></li>
					<li><a href="/admin/handle/pkg/estate-provence/action/list">provence</a></li>
					<li><a href="/admin/handle/pkg/estate-location/action/list">الموقع</a></li>
					<li class="last"><a href="/admin/handle/pkg/estate-type/action/list">النوع</a></li>
				</ul>
			</li>
			<li class="last"><a href="#" class="hassub">إضافة إلى القوائم الفرعية</a>
				<ul>
					<li><a href="/admin/handle/pkg/estate-air-condition/action/add">التدفئة المركزية</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear1/action/add">Live near 1</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear2/action/add">Live near 2</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear3/action/add">Live near 3</a></li>
					<li><a href="/admin/handle/pkg/estate-livenear4/action/add">Live near 4</a></li>
					<li><a href="/admin/handle/pkg/estate-outdoor-amenities/action/add">Outdoor amenities</a></li>
					<li><a href="/admin/handle/pkg/estate-provence/action/add">provence</a></li>
					<li><a href="/admin/handle/pkg/estate-location/action/add">الموقع</a></li>
					<li class="last"><a href="/admin/handle/pkg/estate-type/action/add">النوع</a></li>
				</ul>
			</li>
		</ul>
	</li>
	<li><a href="#">المركبات</a>
		<ul>
			<li><a href="#">إضافة مركبة</a></li>
			<li><a href="#">عرض المركبات</a></li>
			<li class="last"><a href="#" class="hassub">عرض القوائم الفرعية</a>
				<ul>
					<li><a href="/admin/handle/pkg/vehicle-body-color/action/list">الألوان الخارجية</a></li>
					<li><a href="/admin/handle/pkg/vehicle-inside-color/action/list">الألوان الداخلية</a></li>
					<li><a href="/admin/handle/pkg/vehicle-insurance-type/action/list">نوع التأمين</a></li>
					<li><a href="/admin/handle/pkg/vehicle-make/action/list">المصنع</a></li>
					<li><a href="/admin/handle/pkg/vehicle-model/action/list">الموديل</a></li>
					<li><a href="/admin/handle/pkg/vehicle-type/action/list">النوع</a></li>
					<li><a href="/admin/handle/pkg/vehicle-year/action/list">السنة</a></li>
					<li class="last"><a href="/admin/handle/pkg/vehicle-drag-system/action/list">ناقل الحركة</a></li>
				</ul>
			</li>
			<li class="last"><a href="#" class="hassub">إضافة إلى القوائم الفرعية</a>
				<ul>
					<li><a href="/admin/handle/pkg/vehicle-body-color/action/add">الألوان الخارجية</a></li>
					<li><a href="/admin/handle/pkg/vehicle-inside-color/action/add">الألوان الداخلية</a></li>
					<li><a href="/admin/handle/pkg/vehicle-insurance-type/action/add">نوع التأمين</a></li>
					<li><a href="/admin/handle/pkg/vehicle-make/action/add">المصنع</a></li>
					<li><a href="/admin/handle/pkg/vehicle-model/action/add">الموديل</a></li>
					<li><a href="/admin/handle/pkg/vehicle-type/action/add">النوع</a></li>
					<li><a href="/admin/handle/pkg/vehicle-year/action/add">السنة</a></li>
					<li class="last"><a href="/admin/handle/pkg/vehicle-drag-system/action/add">ناقل الحركة</a></li>
				</ul>
			</li>
		</ul>
	</li>
	<li><a href="#">الوسيط</a>
		<ul>
			<li><a href="#">إضافة وسط</a></li>
			<li><a href="#">عرض الأوساط</a></li>
			<li class="last"><a href="#" class="hassub">عرض القوائم الفرعية</a>
				<ul>
					<li class="last"><a href="/admin/handle/pkg/waseet-category/action/list">تصنيف</a></li>
				</ul>
			</li>
			<li class="last"><a href="#" class="hassub">إضافة إلى القوائم الفرعية</a>
				<ul>
					<li class="last"><a href="/admin/handle/pkg/waseet-category/action/add">تصنيف</a></li>
				</ul>
			</li>
		</ul>
	</li>
	<li><a href="/admin/handle/pkg/banner/action/add">الإعلانات</a>
		<ul>
			<li><a href="/admin/handle/pkg/banner/action/add">إضافة إعلان</a></li>
			<li><a href="/admin/handle/pkg/banner/action/list">عرض الإعلانات</a></li>
			<li><a href="/admin/handle/pkg/banner-area/action/add">إضافة منطفة جديدة للإعلان</a></li>
			<li class="last"><a href="/admin/handle/pkg/banner-area/action/list">عرض مناطق الإعلانات</a></li>
		</ul>
	</li>
	<li><a href="/admin/handle/pkg/tag/action/add">السمات</a>
	<ul>
		<li><a href="/admin/handle/pkg/tag/action/addBlackTag">إضافة سمة مشبوهة</a></li>
		<li class="last"><a href="/admin/handle/pkg/tag/action/blackList">عرض السمات المشبوهة</a></li>
	</ul>
	</li>
	<li><a href="/admin/handle/pkg/user/action/add">المستخدمين</a>
	<ul>
		<li><a href="/admin/handle/pkg/user/action/add">إضافة مستخدم</a></li>
		<li><a href="/admin/handle/pkg/user-level/action/add">إضافة نوع مستخدم</a></li>
		<!--<li><a href="/admin/handle/pkg/user-level-permission/action/add">إضافة الصلاحيات</a></li>-->
		<li><a href="/admin/handle/pkg/user/action/list">عرض المستخدمين</a></li>
		<li ><a href="/admin/handle/pkg/user-level/action/list">عرض أنواع المستخدمين</a></li>
		<!--<li class="last"><a href="/admin/handle/pkg/user-level-permission/action/list">عرض صلاحيات المستخدمين</a></li>-->
	</ul>
	</li>
	<li><a href="#">خيارات أخرى</a>
	<ul>
		<li><a href="/admin/handle/pkg/breaknews/action/edit">أخبار عاجلة</a></li>
		<li><a href="/admin/handle/pkg/election/action/edit">بورصة المشرحين</a></li>
		<li><a href="/admin/handle/pkg/classifieds/action/edit">إعلانات مبوبة</a></li>
		<li><a href="/admin/handle/pkg/secrets/action/edit">خفايا وأسرار</a></li>
		<li><a href="/admin/handle/pkg/live/action/edit">البث المباشر</a></li>
		<li><a href="#" class="hassub">اللغات</a>
			<ul>
				<li><a href="/admin/handle/pkg/locale/action/add">إضافة لغة</a></li>
				<li class="last"><a href="/admin/handle/pkg/locale/action/list">عرض اللغات</a></li>
			</ul>
		</li>
		<li class="last"><a href="#" class="hassub">الترجمة</a>
		<ul>
			<li><a href="/admin/handle/pkg/translation/action/add">إضافة كلمة</a></li>
			<li class="last"><a href="/admin/handle/pkg/translation/action/list">عرض الكلمات المترجمة</a></li>
		</ul>
		</li>
	</ul>
	</li>
	<!-- <li class="visitors"><strong>عدد الزوار <span class="orng">(801)</span></strong></li>  -->
</ul>
</div>
<!--end mainnav-->
<?php } ?>