<!--notification-->
<div class="notification" style="<?php print $this->notificationMessageStyle; ?>" ><?php print $this->notificationMessage; ?></div>
<!--end notification-->
<!--success-->
<div class="success" style="<?php print $this->successMessageStyle; ?>" ><?php print $this->successMessage; ?></div>
<!--end success-->
<!--error-->
<div class="error" style="<?php print $this->errorMessageStyle; ?>" ><?php print $this->errorMessage; ?></div>
<!--end error-->
