<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<title>وكالة أنباء سرايا</title>
<link href="/theme/frontend/landing_page/skin/default/css/saraya.css" rel="stylesheet" type="text/css" />
</head>
<body>
<!--containercont-->
<div class="containercont">
    <!--container-->
    <div class="container">
    	<!--logoarea-->
        <div class="logoarea cleaner">
            <h1 class="logoslog">
                <a href="/" class="logo"><img src="/theme/frontend/landing_page/skin/default/images/saraya-logo.png" alt="وكالة أنباء سرايا" title="وكالة أنباء سرايا" width="162" height="110" /></a>
                <span class="slogan"><a href="/"><img src="/theme/frontend/landing_page/skin/default/images/slogan.png" alt="حرية سقفها السماء" width="135" height="17" /></a></span>
            </h1>
            <!--srcharea-->
            <div class="srcharea">
                <h2 class="saryaagency"><a href="/"><img src="/theme/frontend/landing_page/skin/default/images/saraya-agency.png" alt="وكالة سرايا الإخبارية" width="182" height="38" /></a></h2>
            </div>
            <!--end srcharea-->
        </div>
        <!--end logoarea-->
        <!--content-->
        <div class="content">
        	<div class="contbg">
            	<h1 class="sarayanews"><a href="/"><img src="/theme/frontend/landing_page/skin/default/images/sarayanews.png" alt="وكالة سرايا الإخبارية" width="402" height="92" /></a></h1>
                <h2 class="url"><a href="/"><strong>http://www.sarayanews.com</strong></a></h2>
            </div>
        </div>
        <!--end content-->
        <!--footer-->
        <div class="footer">
            جميع الحقوق محفوظة لوكالة سرايا الإخبارية &copy; 2010 <a href="/">sarayanews.com</a>
            
            <a class="fl" href="http://www.direct2inbox.com/" target="_blank"><img width="90" height="53" src="/theme/frontend/default/skin/ar_jo/images/direct2inbox-logo.gif" alt="Direct to inbox effective email marketing" title="Direct to inbox effective email marketing"></a>
            <span class="fl pwredby">تم تصميم وتطوير الموقع بواسطة</span>
        </div>
        <!--end footer-->
    </div>
    <!--end container-->
</div>
<!--end containercont-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17984986-1']);
  _gaq.push(['_setDomainName', '.sarayanews.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</body>
</html>