<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './html/meta.phtml'; ?>
<script>
function getActionsForClass() {
	$.ajax({
	      url: "/admin/handle/pkg/user-level-permission/action/listActions",
	      type: "POST",
	      data: ({class_id : $('#class').val()}),
	      success: function(msg){
	         $('#actionsList').html(msg);
	      }
	   }
	).responseText;
}
</script>
</head>
<body>

<!--container-->
<div class="container">
<?php include './html/header.phtml'; ?>
<?php include './html/menu.phtml'; ?>
<?php include './html/notification.phtml'; ?>
<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<div class="lftnav">
<h3 class="margb1"><?php echo $this->__ ( 'User_Level' ); ?></h3>
<ul>
	<li class="tab active" title="conttab1"><a href="javascript:void(0);"><span><?php echo $this->__ ( 'User_Information' ); ?></span></a></li>
	<li class="tab" title="conttab2"><a href="javascript:void(0);"><span><?php echo $this->__ ( 'User_Advanced' ); ?></span></a></li>
</ul>
</div>
<!--end lftnav-->

<!--ritcont-->
<form action="" method="post" id="frm">
<div class="ritcont">

<!--srch-rslt-->
<div class="srch-rslt">
<h3 class="fl pagetitle margthaf"><?php echo $this->__ ( 'User_Add New User Level Permission' ); ?></h3>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="2" class="emptbtn" type="submit"><?php echo $this->__ ( 'User_Save And Continue Edit' ); ?></button></em></a>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="1" class="emptbtn" type="submit"><?php echo $this->__ ( 'User_Save' ); ?></button></em></a>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="0" class="emptbtn" type="reset"><?php echo $this->__ ( 'User_Reset' ); ?></button></em></a>
<a href="javascript:void(0);" class="backbtn"><em><button name="btn_submit" value="-1" class="emptbtn" type="button" onlcick="javascript:history.go(-1);"><?php echo $this->__ ( 'User_Back' ); ?></button></em></a>
</div>
<!--end srch-rslt-->

<!--conttab1-->
<div class="mytabscont" id="conttab1" style="display: block"><!--entrdata-->
<div class="entrdata">
<h2 class="datatitle"><?php echo $this->__ ( 'User_Information' ); ?></h2>
<div class="entrdcont">
<div class="wdthauto">
	<input type="hidden" id="Id" name="Id" value="<?php print $this->sanitized->Id->value; ?>" /> 
	<input type="hidden" id="token" name="token" value="<?php print $this->sanitized->token->value; ?>" />
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'User_User Level' ); ?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct" id="userLevel" name="userLevel">
		<?php echo $this->userLevelList; ?>
		</select>
		<div class="validat" style="<?php print $this->sanitized->userLevel->errorMessageStyle; ?>">
		<?php print $this->sanitized->userLevel->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'User_Class' ); ?>:</td>
		<td class="lablvalue jstalgntop">
		<select onchange="getActionsForClass();" class="inptslct" id="class" name="class">
		<?php echo $this->classList; ?>
		</select>
		<div class="validat" style="<?php print $this->sanitized->class->errorMessageStyle; ?>">
		<?php print $this->sanitized->class->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'User_Action' ); ?>:</td>
		<td class="lablvalue jstalgntop" id="actionsList">
			<input class="inptflx" type="text" value="" name="action" disabled="disabled" readonly="readonly" />
		<div class="validat" style="<?php print $this->sanitized->action->errorMessageStyle; ?>">
		<?php print $this->sanitized->action->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'User_Permission' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="permission" name="permission"
			value="<?php print $this->sanitized->permission->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->permission->errorMessageStyle; ?>">
		<?php print $this->sanitized->permission->errorMessage; ?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
<!--end entrdata--></div>
<!--end conttab1-->
<!--conttab2-->
<div class="mytabscont" id="conttab2" style="display: none">
<div class="entrdata">
<h2 class="datatitle"><?php echo $this->__ ( 'User_Advanced Settings' ); ?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'User_Comments' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="comment" name="comment"
			value="<?php print $this->sanitized->comment->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->comment->errorMessageStyle; ?>">
		<?php print $this->sanitized->comment->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'User_Options' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="option" name="option"
			value="<?php print $this->sanitized->option->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->option->errorMessageStyle; ?>">
		<?php print $this->sanitized->option->errorMessage; ?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
<!--end entrdata-->
</div>
<!--end conttab2-->
</div>
<!--end ritcont-->
</form>
</div>
<!--end maincont-->
</div>
<!--end content-->
<?php include './html/footer.phtml'; ?>
</div>
<!--end container-->
</body>
</html>
