<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php include './header/meta.phtml'; ?>
<link href="<?php echo $this->defaultSkinCssUrl ?>contactus.css" rel="stylesheet" type="text/css" />
</head>

<body>

<div>

<!--header-->
<!--logoarea-->
		<?php include './header/logo.phtml';?>
<!--end logoarea-->

<!--leaderboard and others -->
		<?php include './banner/topBanner.phtml';?>
<!--end leaderboard and others-->
<!--end header-->


<!--navbar -->
		<?php include './navigation/menu.phtml';?>
<!--end nav-->

    <div class="con">
   	  <div class="hLftPan">
   	  	
   	  	<h3>Contact us</h3>

		<div id="wrapper">
		  <div id="form-div">
		    <form class="form" id="form1" action="/default/contactus" method="post">
		      <p class="name">
		        <input name="name" type="text" id="name" />
		        <label for="name">Name</label>
		      </p>
		      <p class="email">
		        <input name="email" type="text" id="email" />
		        <label for="email">E-mail</label>
		      </p>
		      <p class="text">
		        <textarea name="text" id="comment"></textarea>
		      </p>
		      <p class="submit">
		        <input type="submit" value="Send" />
		      </p>
		    </form>
		  </div>
		 </div>


	<!--right-->
		<?php include './footer/beforeFooter.phtml'; ?>
	<!--end right-->

      </div>

		<div class="cls"></div>
      
  </div>
  
	<!-- footer -->
		<?php include './footer/footer.phtml'; ?>
	<!-- end footer -->

</div>

</body>
</html>