<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './header/meta.phtml'; ?>
</head>
<body>
<!--header-->
<!--logoarea-->
		<?php include './header/logo.phtml';?>
<!--end logoarea-->
<!--end header-->
<!--containcont-->
<div class="containcont">
	<!--containrit-->
	<div class="containrit">
        <!--container-->
        <div class="container cleaner">
        	<!--data-->
            <div class="data cleaner">
            	<!--right-->
					<?php include './right/right.phtml'; ?>
                <!--end right-->
                <!--middledata-->
                <div class="middledata">
                	<!--boxwite-->
                    <div class="boxwite">
                    	<span class="boxwtop"><span><em></em></span></span>
                        <div class="boxwdata">
                        	<p class="margbhaf"><img src="<?php print $this->defaultSkinImagesUrl; ?>title5.gif" alt="كلمة المشرف" width="86" height="16" /></p>
                            <div class="dotpx margb1">
                            	<!--<p>إن ما يتميز به موقع إسلام ويب من شمولية واعتدال وإتقان ، يجعل من الموقع صرحا شامخا ، وبناء قويا في عالم الإنترنت ، فالموقع لا يكتفي بتقديم المعلومات الشرعية من كتب وفتاوى ومقالات وصوتيات ، بل هو أيضا يقدم خدمات استشارية في فنون الطب والثقافة والأسرة ، كما يربط الزائر بواقع الإسلام والمسلمين في كل مكان ، إضافة إلى جهود الموقع لاحتواء جميع فئات المجتمع ، بمختلف مستوياتهم ، كل هذا ضمن منهج أهل السنة والجماعة ، وثوابت ديننا الإسلامي الحنيف المزيد ...</p>-->
                            </div>
                            <p class="margbhaf"><img src="<?php print $this->defaultSkinImagesUrl; ?>title6.gif" alt="أهـداف الموقـع" width="91" height="16" /></p>
                            <ul class="arowlst">
<!--                            	<li>توضيح الصورة الصحيحة للإسلام والمسلمين</li>-->
<!--                                <li>الاهتمام بدعوة غير المسلمين بالطريقة الصحيحة</li>-->
<!--                                <li>توضيح الصورة الصحيحة للإسلام والمسلمين</li>-->
<!--                                <li>الاهتمام بدعوة غير المسلمين بالطريقة الصحيحة</li>-->
                            </ul>
                        </div>
                        <span class="boxwbotom"><span><em></em></span></span>
                    </div>
                    <!--end boxwite-->
                    <!--boxwitegray-->
                    <div class="boxwitegray margt1haf">
                    	<span class="boxwtop"><span><em></em></span></span>
                        <div class="boxwdata">
                        	<p class="margbhaf"><img src="<?php print $this->defaultSkinImagesUrl; ?>title7.gif" alt="قصتي مع الآيات المتشابهة" width="165" height="16" /></p>
                            <ul class="arowlst">
                            	<li>
                                	<a href="#er"><strong>للعلماء المعاصرين وتجرتهم مع الآايات المتشابهة</strong></a>
                                    <p><span class="gray fnt11">للشيخ  فواز الحنين</span></p>
                                </li>
                                <li>
                                	<a href="#er"><strong>للعلماء المعاصرين وتجرتهم مع الآايات المتشابهة</strong></a>
                                    <p><span class="gray fnt11">للشيخ  فواز الحنين</span></p>
                                </li>
                            </ul>
                            <p class="cleaner"><cite class="more fl"><a href="#er">المزيد&nbsp;&raquo;</a></cite></p>
                        </div>
                        <span class="boxwbotom"><span><em></em></span></span>
                    </div>
                    <!--end boxwitegray-->
                    <!--boxwitegray-->
                    <div class="boxwitegray margt1haf">
                    	<span class="boxwtop"><span><em></em></span></span>
                        <ul class="tabs cleaner">
                            <li class="on"><a href="#er">أحـدث الصوتيـات</a></li>
                            <li><a href="#er">أحـدث المرئـيـات</a></li>
                        </ul>
                        <div class="boxwdata">
                            <ul class="thumblst cleaner">
                            	<li><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>audio-thumb.jpg" alt="" width="86" height="65" class="thumb" /></a></li>
                                <li><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>audio-default.jpg" alt="" width="86" height="65" class="thumb" /></a></li>
                                <li><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>audio-thumb.jpg" alt="" width="86" height="65" class="thumb" /></a></li>
                                <li class="last"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>audio-default.jpg" alt="" width="86" height="65" class="thumb" /></a></li>
                            </ul>
                            <p class="cleaner"><cite class="more fl"><a href="#er">المزيد&nbsp;&raquo;</a></cite></p>
                        </div>
                        <span class="boxwbotom"><span><em></em></span></span>
                    </div>
                    <!--end boxwitegray-->
                    <ul class="adsbotomlst cleaner">
                    	<li><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>botomads.jpg" alt="" width="125" height="125" /></a></li>
                        <li><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>botomads.jpg" alt="" width="125" height="125" /></a></li>
                        <li class="last"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>botomads.jpg" alt="" width="125" height="125" /></a></li>
                    </ul>
                </div>
                <!--end middledata-->
            </div>
            <!--end data-->
            <!--left-->
            <?php include './left/left.phtml'?>
            <!--end left-->
        </div>
        <!--end container-->
    </div>
    <!--end containrit-->
</div>
<!--end containcont-->
<!-- footer -->
<?php include './footer/footer.phtml'; ?>
<!-- end footer -->
</body>
</html>