<!--begin paging-->
<?php

if (isset ( $this->paging->pages ) and ! empty ( $this->paging->pages )) {
	echo '<div class="paging">' . PHP_EOL;
	if (isset($this->paging->previous) and ! is_null ( $this->paging->previous )) {
		if (! empty ( $this->paging->previous->class )) {
			echo '<span class="' . $this->paging->previous->class . '">&laquo;&nbsp;' . $this->__ ( 'Previous' ) . '</span>';
		} else {
			echo '<a href="' . $this->paging->previous->uri . '">&laquo;&nbsp;' . $this->__ ( 'Previous' ) . '</a>';
		}
	} else {
		echo '<span>&laquo;&nbsp;' . $this->__ ( 'Previous' ) . '</span>';
	}
	foreach ( $this->paging->pages as $page ) {
		if (! empty ( $page->class )) {
			echo '<span class="' . $page->class . '">' . $page->id . '</span>';
		} else {
			echo '<a href="' . $page->uri . '">' . $page->id . '</a>';
		}
	}
	if (isset($this->paging->next) and ! is_null ( $this->paging->next )) {
		if (! empty ( $this->paging->next->class )) {
			echo '<span class="' . $this->paging->next->class . '">' . $this->__ ( 'next' ) . '&nbsp;&raquo;</span>';
		} else {
			echo '<a href="' . $this->paging->next->uri . '">' . $this->__ ( 'next' ) . '&nbsp;&raquo;</a>';
		}
	} else {
		echo '<span>' . $this->__ ( 'next' ) . '&nbsp;&raquo;</span>';
	}
	echo '</div>' . PHP_EOL;
}
?>
<!--end paging-->
