<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php include './header/meta.phtml'; ?>
</head>

<body>

<div>

<!--header-->
<!--logoarea-->
		<?php include './header/logo.phtml';?>
<!--end logoarea-->
<!--end header-->


<!--navbar -->
		<?php include './navigation/menu.phtml';?>
<!--end nav-->

    <div class="con">
    	
    	
    	
    	<div class="lftPan">
   	  <h1>Building in Doha</h1>
   		<div>
            	<div class="photo"><img height="243" width="324" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_landlots.png"></div>
            	<div>
                  <div class=" photoSmallTtl">More views</div>
                    <div class="photoSmall">
                        <img height="52" width="52" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_photo_small1.png">
                        <img height="52" width="52" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_photo_small1.png">
                        <img height="52" width="52" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_photo_small1.png">
                        <img height="52" width="52" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_photo_small1.png">
                        <img height="52" width="52" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_photo_small1.png">
                        <img height="52" width="52" alt="" src="<?php echo $this->defaultSkinImagesUrl?>sample_photo_small1.png">
                        <div class="cls"></div>
                    </div>
        		</div>
       	</div>
			<!--video -->
					<?php include './blocks/video.phtml';?>
			<!--end video-->
			
			
			<!--map location -->
					<?php include './blocks/mapLocation.phtml';?>
			<!--end map location-->
            <div>
           	  <h2 title="Price Index of BMW - 225i 2005">Price Index</h2>
              <div class="grid">
               	<div>Max:1,000,000 QAR</div>
                    <div>Avarage:1,200,000 QAR</div>
                    <div>Min:1,400,000 QAR</div>
              </div>
            </div>
            
            
			<!--bankloan -->
					<?php include './blocks/bankLoan.phtml';?>
			<!--end bankloan-->
        
        
      </div>
      
      
      <div class="midPan">
		<!--social -->
				<?php include './blocks/socialMedia.phtml';?>
		<!--end social-->
  <div class="price">
        	<div class="priceNum">Price: QAR 1,000,000</div>
            <div class="priceContact">
            	<div>
               	  <div class="ttl">Contact Details:</div>
               	  <div class="data">
                	Phone: +974-44430285<br>
                    Fax: +974-44356125<br>
                    Mobile: +974-55867235
                </div>
                	<div class="cls"></div>
                </div>
                <div>
                	<div class="ttl">Negotiable:</div>
                    <div class="data">Yes</div>
                    <div class="cls"></div>
            </div>
            	<div>
                	<div class="ttl">Seller type:</div>
                    <div class="data">Person</div>
                    <div class="cls"></div>
       		  </div>
                <div>
                	<div class="ttl">Advertise date:</div>
                    <div class="data">20-11-2011</div>
                    <div class="cls"></div>
              </div>
            </div>
        </div>
  <div>
   	    <h2 title="BMW - 225i 2005 Specifications">Realestate Specifications</h2>
<div class="grid dataListBig">
               	<div>
               	  <div class="ttl">Property status</div>
                  <div class="data">2 bids</div>
                  <div class="cls"></div>
</div>
                <div>
                	<div class="ttl">Real estate type</div>
                    <div class="data">18.000 Km</div>
                    <div class="cls"></div>
</div>
                <div>
                    <div class="ttl">Location (Cities)</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
    </div>
                <div>
                    <div class="ttl">Map Location</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
          </div>
                <div>
                    <div class="ttl">Area</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Age</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Rooms</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Bath rooms</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Parking Garage</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Stories</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Extra Feature</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Furniture</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Air Condition</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Outdoor amenities</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
                <div>
                    <div class="ttl">Live near</div>
                    <div class="data">156.000 Q.R.</div>
                    <div class="cls"></div>
                </div>
   		</div>
        </div>
      </div>
      

      
      
<!--right-->
	<?php include './right/right.phtml'; ?>
<!--end right-->
      
      
  </div>
  
  
  	<!--right-->
		<?php include './footer/beforeFooter.phtml'; ?>
	<!--end right-->
  
  
  
	<!-- footer -->
		<?php include './footer/footer.phtml'; ?>
	<!-- end footer -->


</div>

</body>
</html>