		<div class="bfooter">
			<?php if ($this->innerFooter === true)
					echo '<div class="bfooterCon">';
			?>
			
			<div class="part">
              <ul>
                <li><a href="#">Careers</a></li>
                <li><a href="#">About us</a></li>
                <li><a href="#">Store locations</a></li>
                <li><a href="#">Online store</a></li>
              </ul>
            </div>
       		<div class="part">
	       	  <ul>
	       	    <li><a href="#">Returns</a></li>
	            <li><a href="#">Customer service</a></li>
	            <li><a href="#">Gift cards</a></li>
	            <li><a href="#">Extended service plan</a></li>
	          </ul>
      		</div>
   			<div class="part">
       	  	  <ul>
       	    	<li><a href="#">Site map</a></li>
           	 	<li><a href="#">About us</a></li>
            	<li><a href="#">Store locations</a></li>
            	<li><a href="#">Online store</a></li>
          	  </ul>
      		</div>
   			<div class="cls"></div>
   			<?php if ($this->innerFooter === true)
					echo '</div>';
			?>
  		</div>