  <div class="footer">
  <div class="footerCon">
    	<ul>
        	<li class="first"><a href="#">Site Map</a></li>
          <li><a href="#">Search Terms</a></li>
          <li><a href="#">Advanced Search</a></li>
          <li><a href="#">Orders and Returns</a></li>
          <li class="last"><a href="<?php echo $this-> rootUrl ?>default/contactus">Contact Us</a></li>
        </ul>
        <div class="cls"></div>
        <div>Copyright © 2011 car2dar.com. All rights reserved.</div>
    </div>
  </div>