<p class="botombg"><span><em></em></span></p>
<div class="footer">
    <ul class="footlnks">
        <li><a href="#er">الصفحة الرئيسية</a></li>
        <li><a href="#er">كتاب الضبط بالتقعيد</a></li>
        <li><a href="#er">أهداف الموقع</a></li>
        <li><a href="#er">مواقع قرآنية</a></li>
        <li><a href="#er">برامج قرآنية</a></li>
        <li><a href="#er">بحوث علمية</a></li>
        <li><a href="#er">فتآوى قرانية</a></li>
        <li><a href="#er">صوتيات</a></li>
        <li class="last"><a href="#er">مرئيات</a></li>
    </ul>
    <p class="copyrights-outer">جميع الحقوق محفوظة لموقع الضبط بالتقعيد &copy; 2011 <a href="#er">www.mutashabih.com</a></p>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17984986-1']);
  _gaq.push(['_setDomainName', '.sarayanews.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>