<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
include './html/meta.phtml';
?>
</head>
<body class="claro">

<!--container-->
<div class="container">
<?php
include './html/header.phtml';
?>
<?php

include './html/menu.phtml';
?>
<?php

include './html/notification.phtml';
?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav--> <!--end lftnav--> <!--ritcont-->

<?php
echo $this->form;
echo $this->inlineScript ();
?>

</div>
<!--end maincont--></div>
<!--end content-->
<?php
include './html/footer.phtml';
?>
</div>
<!--end container-->
</body>
</html>
