<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './html/meta.phtml'; ?>
</head>
<body class="tundra">

<!--container-->
<div class="container">
<?php include './html/header.phtml'; ?>
<?php include './html/menu.phtml'; ?>
<?php include './html/notification.phtml'; ?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<!--end lftnav-->

<!--srch-rslt-->
<div class="srch-rslt">
<h3 class="fl pagetitle margthaf"><?php echo $this->__ ( 'Vehicle_For_Rent Add New' ); ?></h3>
<a href="javascript:history.go(-1)" class="backbtn"><em><button name="btn_submit" value="-1" class="emptbtn" type="button" onlcick="javascript:history.go(-1);"><?php echo $this->__ ( 'Vehicle_Back' ); ?></button></em></a>
</div>
<!--end srch-rslt-->
 <!-- <div dojoType="dojox.data.QueryReadStore" jsId="testStore" url="getContactAjax"></div> -->
<!--ritcont-->
<div class="entrdata">
	<div class="entrdcont">
		<div class="wdthauto">
			<?php 
			 echo $this->form;
			 echo $this->dojo ();
			?>
		</div>
	</div>
</div>

<script type="text/javascript">
dojo.ready(function() {
    dojo.connect(dijit.byId("contact_nid_cr"), 'onChange', function (val) {
		dojo.xhrPost( {
			content: {
		      contactNIDCR: val,
		    },
		    url: "/admin/handle/pkg/vehicle-for-rent/action/getContactAjax",
		    //handleAs: "text",
		    handleAs: "json",
		    //timeout: 100000,
		    preventCache: true,

			load: function(response, ioArgs) {
				for(var i in response){
           			//console.log("key", i, "value", response[i]);
           			dijit.byId(i).attr('value', '');
           			dijit.byId(i).attr('value', response[i]);
        		}
			return response;
			},		
		});
	});
});
</script>


</div>
<!--end maincont-->
</div>
<!--end content-->
<?php include './html/footer.phtml'; ?>
</div>
<!--end container-->
</body>
</html>