<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './header/meta.phtml'; ?>
</head>
<body>
<!--header-->
<!--logoarea-->
		<?php include './header/logo.phtml';?>
<!--end logoarea-->
<!--end header-->
<!--containcont-->
<div class="containcont">
	<!--containrit-->
	<div class="containrit">
        <!--container-->
        <div class="container cleaner">
        	<!--data-->
            <div class="data cleaner">
            	<!--ritpanel-->
            		<?php include './right/right.phtml'; ?>
                <!--end ritpanel-->
                <!--middledata-->
                <div class="middledata">
					<!--tree-->
		                <ul class="tree cleaner">
		                    <li><a href="/">الصفحة الرئيسية</a></li>
		                    <li><?php echo $this->cleanHtml ( $this->categoryDetails['title'] ); ?></li>
		               </ul>
		              <!--end tree-->
                	<!--boxwite-->
                    <div class="boxwite">
                    	<span class="boxwtop"><span><em></em></span></span>
                        <div class="boxwdata">
                        	<h2 class="title"><?php echo $this->cleanHtml ( $this->categoryDetails['title'] ); ?></h2>
                            <!--newslst-->
                            <ul class="newslstsep">
                            <?php 
			                	$countVideoList  = count($this->videoList );
			                	for($i=0; $i<$countVideoList  ; $i++) {
		                	?>
                                <li class="cleaner">
                                <?php  if (isset ($this->videoList[$i]['imageUrl'])) { ?>
                                  <a href="/object-video/view/id/<?php echo $this->videoList[$i]['id']; ?>/title/<?php echo $this->videoList[$i]['title']; ?>" title="<?php echo $this->videoList[$i]['title']; ?>"><img src="<?php echo $this->videoList[$i]['imageUrl']; ?>" alt="<?php echo $this->videoList[$i]['photo_alias']; ?>" title="<?php echo $this->videoList[$i]['photo_alias']; ?>" class="thumb fr" /></a>
                                  <?php } ?>     
                                    <div>
                                        <h2><a href="/object-video/view/id/<?php echo $this->videoList[$i]['id']; ?>/title/<?php echo $this->videoList[$i]['title']; ?>"><?php echo $this->cleanHtml ( $this->videoList[$i]['alias'] ); ?></a></h2>
                                        <cite class="date"><?php echo $this->videoList[$i]['date_added']; ?></cite>
                                        <?php if(!is_numeric($this->videoList[$i]['original_author'])) {?>
                                        <p><?php echo $this->videoList[$i]['original_author']; ?></p>
                                        <?php } ?>
                                    </div>
                                </li>
                               <?php } ?>
                            </ul>
                            <!--end newslst-->
                            <!--begin paging-->
								<?php include './paging.phtml';?>
								<br />
                            <!--end paging-->
                        </div>
                        <span class="boxwbotom"><span><em></em></span></span>
                    </div>
                    <!--end boxwite-->
                </div>
                <!--end middledata-->
            </div>
            <!--end data-->
           <!--left-->
            <?php include './left/left.phtml'?>
            <!--end left-->
        </div>
        <!--end container-->
    </div>
    <!--end containrit-->
</div>
<!--end containcont-->
<!-- footer -->
<?php include './footer/footer.phtml'; ?>
<!-- end footer -->
</body>
</html>