        <ul class="belowbanrs cleaner">
            <li><?php echo str_replace(array('#XXX#', '#YYY#'), array(300, 70), $this->bannersList['homepage-center-right-2']['content']); ?></li>
            <li><?php echo str_replace(array('#XXX#', '#YYY#'), array(300, 70), $this->bannersList['homepage-center-right-3']['content']); ?></li>
            <li class="last"><?php echo str_replace(array('#XXX#', '#YYY#'), array(300, 70), $this->bannersList['homepage-center-left-2']['content']); ?></li>
        </ul>