
<div class="topbanners">
<p class="banner"><?php
echo str_replace ( array ('#XXX#', '#YYY#' ), array (300, 70 ), $this->bannersList ['homepage-top-left-1'] ['content'] );
?></p>
<p class="banner"><?php
echo str_replace ( array ('#XXX#', '#YYY#' ), array (300, 70 ), $this->bannersList ['homepage-top-left-2'] ['content'] );
?></p>
<p class="banner"><?php
echo str_replace ( array ('#XXX#', '#YYY#' ), array (300, 70 ), $this->bannersList ['homepage-top-left-3'] ['content'] );
?></p>
<p class="banner"><?php
echo str_replace ( array ('#XXX#', '#YYY#' ), array (300, 70 ), $this->bannersList ['homepage-top-left-4'] ['content'] );
?></p>
<p class="banner"><?php
echo str_replace ( array ('#XXX#', '#YYY#' ), array (300, 70 ), $this->bannersList ['homepage-top-left-5'] ['content'] );
?></p>
</div>
