<div class="adsTop">
   <div class="adsTopCon">
  	 <table border="0" cellspacing="0" cellpadding="2">
          <tr>
            <td colspan="3" valign="top"><img src="<?php echo $this->defaultSkinImagesUrl ?>728x90px.png" width="728" height="90" /></td>
            <td rowspan="2"><img src="<?php echo $this->defaultSkinImagesUrl ?>180x180px.png" width="180" height="150" alt="" /></td>
          </tr>
          <tr>
            <td><img src="<?php echo $this->defaultSkinImagesUrl ?>234x60px.png" width="234" height="60" alt="" /></td>
            <td align="center"><img src="<?php echo $this->defaultSkinImagesUrl ?>234x60px.png" width="234" height="60" alt="" /></td>
            <td align="right"><img src="<?php echo $this->defaultSkinImagesUrl ?>234x60px.png" width="234" height="60" alt="" /></td>
          </tr>
        </table>
   </div>
</div>