<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
include './html/meta.phtml';
?>
</head>
<body>

<!--container-->
<div class="container">
<?php
include './html/header.phtml';
?>
<?php

include './html/menu.phtml';
?>
<?php

include './html/notification.phtml';
?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<div class="lftnav">
<h3 class="margb1"><?php
echo $this->__ ( 'Translation_Add New Translation' );
?></h3>
<ul>
	<li class="tab active" title="conttab1"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Translation_Information' );
	?></span></a></li>
	<li class="tab" title="conttab2"><a href="javascript:void(0);"><span><?php
	echo $this->__ ( 'Translation_Advanced' );
	?></span></a></li>
</ul>
</div>
<!--end lftnav--> <!--ritcont-->
<form action="" method="post">
<div class="ritcont"><!--srch-rslt-->
<div class="srch-rslt"><!--<h3 class="fl pagetitle margthaf"><?php
echo $this->__ ( 'Translation_Add New Translation' );
?></h3>-->
<a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="2" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Translation_Save And Continue Edit' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="1" class="emptbtn" type="submit"><?php
echo $this->__ ( 'Translation_Save' );
?></button>
</em></a> <a href="javascript:void(0);" class="save-btn"><em>
<button name="btn_submit" value="0" class="emptbtn" type="reset"><?php
echo $this->__ ( 'Translation_Reset' );
?></button>
</em></a> <a href="javascript:history.go(-1)" class="backbtn"><em>
<button name="btn_submit" value="-1" class="emptbtn" type="button"
	onlcick="javascript:history.go(-1);"><?php
	echo $this->__ ( 'Translation_Back' );
	?></button>
</em></a></div>
<!--end srch-rslt--> <!--conttab1-->
<div class="mytabscont" id="conttab1" style="display: block"><!--entrdata-->
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Translation_Information' );
?></h2>
<div class="entrdcont">
<div class="wdthauto"><input type="hidden" id="Id" name="Id"
	value="<?php
	print $this->sanitized->Id->value;
	?>" /> <input
	type="hidden" id="token" name="token"
	value="<?php
	print $this->sanitized->token->value;
	?>" />
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Translation_Title' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="label" name="label"
			value="<?php
			print $this->sanitized->label->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->label->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->label->errorMessage;
		?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Translation_Translation' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="translation" name="translation"
			value="<?php
			print $this->sanitized->translation->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->translation->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->translation->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	if (! empty ( $this->localeList )) {
		?>
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Translation_Locale' );
		?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct" id="locale"
			name="locale">
		<?php
		echo $this->localeList;
		?>
		</select>
		<div class="validat" style="<?php
		print $this->sanitized->locale->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->locale->errorMessage;
		?></div>
		</td>
	</tr>
	<?php
	} else {
		?>
	<tr>
		<td><input type="hidden" name="locale" value="0" /></td>
	</tr>
	<?php
	}
	?>
</table>
</div>
</div>
</div>
<!--end entrdata--></div>
<!--end conttab1--> <!--conttab2-->
<div class="mytabscont" id="conttab2" style="display: none">
<div class="entrdata">
<h2 class="datatitle"><?php
echo $this->__ ( 'Translation_Advanced Settings' );
?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php
		echo $this->__ ( 'Translation_Comments' );
		?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="comment" name="comment"
			value="<?php
			print $this->sanitized->comment->value;
			?>" />
		<div class="validat" style="<?php
		print $this->sanitized->comment->errorMessageStyle;
		?>">
		<?php
		print $this->sanitized->comment->errorMessage;
		?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
<!--end entrdata--></div>
<!--end conttab2--></div>
<!--end ritcont-->
</form>
</div>
<!--end maincont--></div>
<!--end content-->
<?php
include './html/footer.phtml';
?>
</div>
<!--end container-->
</body>
</html>
