
<div class="boxwitegray margt1haf"><span class="boxwtop"><span><em></em></span></span>
<div class="boxwdata">
<h2 class="title">تعـلـيـقـات الـقـراء</h2>
<ul class="comments">
                                        <?php
																																								$countCommentList = count ( $this->commentList );
																																								for($i = 0; $i < $countCommentList; $i ++) {
																																									?>
                                            <li<?php
																																									echo ($i == $countCommentList - 1) ? 'class="last"' : '';
																																									?>">
	<div class="cleaner by-user">
	<p><b>بواسطة: </b><a href="#er"><?php
																																									echo $this->cleanHtml ( $this->commentList [$i] ['user_id'] );
																																									?></a></p>
	<p class="by-date"><cite class="date"><?php
																																									echo $this->commentList [$i] ['date_added'];
																																									?></cite></p>
	</div>
	<p class="comment-txt"><?php
																																									echo $this->cleanHtml ( $this->commentList [$i] ['content'] );
																																									?></p>
	</li>
                                        <?php
																																								}
																																								?>
                                    

</div>
<span class="boxwbotom"><span><em></em></span></span></div>