<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include './html/meta.phtml'; ?>
</head>
<body>

<!--container-->
<div class="container">
<?php include './html/header.phtml'; ?>
<?php include './html/menu.phtml'; ?>
<?php include './html/notification.phtml'; ?>

<!--content-->
<div class="content"><!--maincont-->
<div class="maincont cleaner"><!--lftnav-->
<div class="lftnav">
<h3 class="margb1"><?php echo $this->__ ( 'Theme_Layout' ); ?></h3>
<ul>
	<li class="tab active" title="conttab1"><a href="javascript:void(0);"><span><?php echo $this->__ ( 'Theme_Information' ); ?></span></a></li>
	<li class="tab" title="conttab2"><a href="javascript:void(0);"><span><?php echo $this->__ ( 'Theme_Advanced' ); ?></span></a></li>
</ul>
</div>
<!--end lftnav-->

<!--ritcont-->
<form action="" method="post">
<div class="ritcont">

<!--srch-rslt-->
<div class="srch-rslt">
<h3 class="fl pagetitle margthaf"><?php echo $this->__ ( 'Theme_Add New Layout' ); ?></h3>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="2" class="emptbtn" type="submit"><?php echo $this->__ ( 'Theme_Save And Continue Edit' ); ?></button></em></a>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="1" class="emptbtn" type="submit"><?php echo $this->__ ( 'Theme_Save' ); ?></button></em></a>
<a href="javascript:void(0);" class="save-btn"><em><button name="btn_submit" value="0" class="emptbtn" type="reset"><?php echo $this->__ ( 'Theme_Reset' ); ?></button></em></a>
<a href="javascript:history.go(-1)" class="backbtn"><em><button name="btn_submit" value="-1" class="emptbtn" type="button" onlcick="javascript:history.go(-1);"><?php echo $this->__ ( 'Theme_Back' ); ?></button></em></a>
</div>
<!--end srch-rslt-->
<!--conttab1-->
<div class="mytabscont" id="conttab1"><!--entrdata-->
<div class="entrdata">
<h2 class="datatitle"><?php echo $this->__ ( 'Theme_Information' ); ?></h2>
<div class="entrdcont">
<div class="wdthauto">
	<input type="hidden" id="Id" name="Id" value="<?php print $this->sanitized->Id->value; ?>" /> 
	<input type="hidden" id="token" name="token" value="<?php print $this->sanitized->token->value; ?>" />
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Title' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="title" name="title"
			value="<?php print $this->sanitized->title->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->title->errorMessageStyle; ?>">
		<?php print $this->sanitized->title->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Label' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			name="label" id="label"
			value="<?php echo $this->sanitized->label->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->label->errorMessageStyle; ?>"><?php print $this->sanitized->label->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Description' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="description" name="description"
			value="<?php print $this->sanitized->description->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->description->errorMessageStyle; ?>">
		<?php print $this->sanitized->description->errorMessage; ?></div>
		</td>
	</tr>
	<?php if (!empty($this->directionList)) {?>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Direction' ); ?>:</td>
		<td class="lablvalue jstalgntop"><select class="inptslct"
			id="direction" name="direction">
			<?php echo $this->directionList; ?>
		</select>
		<div class="validat" style="<?php print $this->sanitized->direction->errorMessageStyle; ?>">
		<?php print $this->sanitized->direction->errorMessage; ?></div>
		</td>
	</tr>
	<?php } else { ?>
	<tr>
		<td><input type="hidden" name="direction" value="lrt" /></td>
	</tr>
	<?php }?>
	<tr>
		<td class="lable jstalgntop">&nbsp;</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="checkbox" class="intchk fl"
				id="default" name="default" value="Yes" 
				<?php echo ('Yes' == $this->sanitized->default->value) ? 'checked="checked"' : ''; ?> /> <label for="default" class="inptlabl fl"><?php echo $this->__ ( 'Theme_Default' ); ?></label><br />
			<div class="validat" style="<?php print $this->sanitized->default->errorMessageStyle; ?>">
		<?php print $this->sanitized->default->errorMessage; ?></div>
			</li>
			<li class="cleaner"><input type="checkbox" class="intchk fl"
				id="published" name="published" value="Yes" 
				<?php echo ('Yes' == $this->sanitized->published->value) ? 'checked="checked"' : ''; ?> /> <label for="published" class="inptlabl fl"><?php echo $this->__ ( 'Theme_Published' ); ?></label><br />
			<div class="validat" style="<?php print $this->sanitized->published->errorMessageStyle; ?>">
		<?php print $this->sanitized->published->errorMessage; ?></div>
			</li>
			<li class="cleaner"><input type="checkbox" id="approved"
				class="intchk fl" name="approved" value="Yes" 
				<?php echo ('Yes' == $this->sanitized->approved->value) ? 'checked="checked"' : ''; ?> /> <label for="approved" class="inptlabl fl"><?php echo $this->__ ( 'Theme_Approved' ); ?></label><br />
			<div class="validat" style="<?php print $this->sanitized->approved->errorMessageStyle; ?>">
		<?php print $this->sanitized->approved->errorMessage; ?></div>
			</li>
		</ul>
		</td>
	</tr>
	<?php if (!empty($this->afterIdList)) {?>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Order' ); ?>:</td>
		<td class="lablvalue jstalgntop">
		<ul class="lstsopt">
			<li class="cleaner"><input type="radio" id="order"
				class="intchk fl" name="order" value="0"
				<?php if (0 == $this->sanitized->order->value || 'after' != $this->sanitized->order->value ) {
				echo 'checked="checked"';	
				} ?> /> <label for="order" class="inptlabl fl"><?php echo $this->__ ( 'Theme_At the beginning of the list' ); ?></label><br />
			<div class="validat" style="<?php print $this->sanitized->order->errorMessageStyle; ?>">
		<?php print $this->sanitized->order->errorMessage; ?></div>
			</li>
			<li class="cleaner">
				<input type="radio" id="order" class="intchk fl" name="order" value="-1"
				<?php echo (-1 == $this->sanitized->order->value) ? 'checked="checked"' : ''; ?> /> 
				<label for="order" class="inptlabl fl"><?php echo $this->__ ( 'Theme_After' ); ?></label><br />
				<select class="inptslct" id="afterId" name="afterId">
				<?php echo $this->afterIdList; ?>
				</select>
			<div class="validat" style="<?php print $this->sanitized->afterId->errorMessageStyle; ?>">
		<?php print $this->sanitized->afterId->errorMessage; ?></div>
			</li>
		</ul>
		</td>
	</tr>
	<?php } else { ?>
	<tr>
		<td><input type="hidden" name="order" value="0" /></td>
	</tr>
	<?php }?>
</table>
</div>
</div>
</div>
<!--end entrdata--></div>
<!--end conttab1--> <!--conttab2-->
<div class="mytabscont" id="conttab2" style="display: none"><!--entrdata-->
<div class="entrdata">
<h2 class="datatitle"><?php echo $this->__ ( 'Theme_Advanced' ); ?></h2>
<div class="entrdcont">
<div class="wdthauto">
<table class="formlist">
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Publish From' ); ?>:</td>
		<td class="lablvalue jstalgntop">
		<div class="calen_beside"><input type="text"
			class="inpttxt wdth70 slctdate" id="slct_date2" name="publishFrom"
			value="<?php print $this->sanitized->publishFrom->value; ?>" /></div>
		<div class="validat" style="<?php print $this->sanitized->publishFrom->errorMessageStyle; ?>">
		<?php print $this->sanitized->publishFrom->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Publish To' ); ?>:</td>
		<td class="lablvalue jstalgntop">
		<div class="calen_beside"><input type="text"
			class="inpttxt wdth70 slctdate" id="slct_date3" name="publishTo"
			value="<?php print $this->sanitized->publishTo->value; ?>" /></div>
		<div class="validat" style="<?php print $this->sanitized->publishTo->errorMessageStyle; ?>">
		<?php print $this->sanitized->publishTo->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Comments' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="comment" name="comment"
			value="<?php print $this->sanitized->comment->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->comment->errorMessageStyle; ?>">
		<?php print $this->sanitized->comment->errorMessage; ?></div>
		</td>
	</tr>
	<tr>
		<td class="lable jstalgntop"><?php echo $this->__ ( 'Theme_Options' ); ?>:</td>
		<td class="lablvalue jstalgntop"><input type="text" class="inptflx"
			id="option" name="option"
			value="<?php print $this->sanitized->option->value; ?>" />
		<div class="validat" style="<?php print $this->sanitized->option->errorMessageStyle; ?>">
		<?php print $this->sanitized->option->errorMessage; ?></div>
		</td>
	</tr>
</table>
</div>
</div>
</div>
<!--end entrdata-->
</div>
<!--end conttab2-->
</div>
<!--end ritcont-->
</form>
</div>
<!--end maincont-->
</div>
<!--end content-->
<?php include './html/footer.phtml'; ?>
</div>
<!--end container-->
</body>
</html>
