<div class="header">
	<div class="headerCon">
		<div class="logo"><a href="<?php echo $this -> rootUrl?>"><img src="<?php echo $this->defaultSkinImagesUrl ?>logo_car2dar.png" width="169" height="78" alt="Car2Dar" /></a></div>
        <div class="menu">
        	<div>
            	<div class="flag"><img src="<?php echo $this->defaultSkinImagesUrl ?>sample_flag.png" width="27" height="17" alt="" /></div>
              <div class="fl">
               	<select><option>Qatar</option></select>
              </div>
              <div class="fl">
                	<select><option>Kilometer</option></select>
              </div>
              <div class="fl">
                	<select><option>US Dollar</option></select>
              </div>
<div class="lang">
                	<div class="flag"><img src="<?php echo $this->defaultSkinImagesUrl ?>lang-en.png" width="14" height="11" alt="" /></div>
                <div class="fr">Change Language <img src="<?php echo $this->defaultSkinImagesUrl ?>lang_arrow.png" width="7" height="5" alt="" /></div>
              </div>
                <div class="cls"></div>
            </div>
            <div>
				<ul>
					<?php 
					foreach ( $this->menuList['upper_menu'] as $key => $value) {
						echo '<li><a href="' . $this -> rootUrl . $value['link'] . '">' . $value['label'] . '</a></li>';
					} 
					?>
                	<!-- <li><a href="<?php echo $this -> rootUrl?>">Home</a></li>
                    <li><a href="<?php echo $this -> rootUrl?>default/aboutus">About us</a></li>
                    <li><a href="<?php echo $this -> rootUrl?>default/mission">Mission</a></li>
                    <li><a href="<?php echo $this -> rootUrl?>default/services">Services</a></li> -->
                    <li class="last"><a href="<?php echo $this -> rootUrl?>default/contactus">Contact us</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>