<title><?php print $this->cleanHtml ( $this->pageTitle ); ?></title>
<meta content="<?php print $this->cleanHtml ( $this->metaKeywords ); ?>" name="Keywords" />
<meta content="<?php print $this->cleanHtml ( $this->metaDescription ); ?>" name="Description" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<link href="<?php echo $this->defaultSkinCssUrl ?>styles_car2dar.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php print $this->defaultSkinJsUrl; ?>jquery-1.4.4.min.js"></script>


<!-- <script type="text/javascript" src="<?php print $this->defaultSkinJsUrl; ?>index.js"></script>
<script type="text/javascript" src="<?php print $this->defaultSkinJsUrl; ?>jquery.timers-1.2.js.txt"></script>
<script type="text/javascript" src="<?php print $this->defaultSkinJsUrl; ?>jquery.cycle.all.min.js"></script> -->

