
<!--databelow-->
<ul class="cleaner databelow">
             <?php
													include 'bottomArea/newsSarayaWriters.phtml';
													?>
             <?php
													include 'bottomArea/newsArticles.phtml';
													?>
              <?php
														include 'bottomArea/newsContributions.phtml';
														?>
              <?php
														include 'bottomArea/newsHashimCorner.phtml';
														?>
        </ul>
<!--end databelow-->
<!--tiny block-->
<ul class="cleaner hbpc">
           <?php
											include 'bottomArea/newsComplains.phtml';
											?>
             <?php
													include 'bottomArea/newsDies.phtml';
													?>
           <?php
											include 'bottomArea/newsOccasions.phtml';
											?>
        </ul>
<!--end tiny block-->
<!--small block-->
<ul class="cleaner hbpc">
           <?php
											include 'bottomArea/newsHelpMe.phtml';
											?>
           <?php
											include 'bottomArea/newsDiscussion.phtml';
											?>
		   <?php
					include 'bottomArea/newsBeauty.phtml';
					?>
        </ul>
<!--end small block-->