        <div class="classads_btn">
            <ul class="cleaner">
                <li class="frst"><span class="classadlbl"></span></li>
                <li class="clasad1"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="" width="127" height="26" /></a></li>
                <li class="clasad2"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="" width="127" height="26" /></a></li>
                <li class="clasad3"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="" width="127" height="26" /></a></li>
                <li class="clasad4"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="" width="127" height="26" /></a></li>
                <li class="clasad5"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="" width="127" height="26" /></a></li>
                <li class="clasad6"><a href="#er"><img src="<?php print $this->defaultSkinImagesUrl; ?>spacer.gif" alt="" width="127" height="26" /></a></li>
            </ul>
        </div>