<!--
        <div class="tickerbelow">
            <div class="tickerlft cleaner">
                <span class="smarketlbl"></span>
                <marquee onmouseover="this.stop()" onmouseout="this.start()" scrollamount="3" scrolldelay="50" direction="right" class="marquee cleaner">
                    <a href="#er">#########</a>
                    <a href="#er">#########</a>
                    <a href="#er">#########</a>
                </marquee>
            </div>
        </div>
        
-->