		<div class="contrit">
                <!--jortoday-->
                <?php include 'rightColumn/newsJordanToday.phtml'; ?>
                <!--end jortoday-->
            	<!--cleaner-->
                <div class="cleaner" style="margin-top: 10px;">
                	<!--hafwdth-->
                	<div class="hafwdth fr">
                    	<!--fannbox-->
                    	<?php include 'rightColumn/newsEntertainment.phtml'; ?>
                        <!--end fannbox-->
                    </div>
                    <!--end hafwdth-->
                    <!--hafwdth-->
                	<div class="hafwdth fl">
                    	<!--domenbox-->
                    	<?php include 'rightColumn/newsSports.phtml'; ?>
                        <!--end domenbox-->
                    </div>
                    <!--end hafwdth-->
                </div>
                <!--end cleaner-->
                <?php include './banner/centerBanner.phtml'; ?>
                <!--politic-news-->
              	<?php include 'rightColumn/newsPolitical.phtml'; ?>
                <!--end politic-news-->
            </div>